scieloorg/opac-airflow

airflow/dags/read_documetstore_changes.py, docker-compose.yml
Adiciona a capacidade de realizar tentativas no ponto de integração com o Kernel
Na Dag: dags/read_documetstore_changes.py
Acessando a interface administrativa do AirFlow e ligando a DAG: documentstore_changes 
Não há.
Não há. 
Não há.
=> Adiciona retry para as funções que utilizam requests e liga o envio de e-mail em caso de falha

airflow/dags/kernel_changes.py, docker-compose.yml
Adiciona a capacidade de registrarmos a conexão do OPAC no modelo airflow.models.Connection
Na Dag: dags/kernel_changes.py
Veja: 
opac_conn: 
kernel_conn:
Adicionado no item anterior
tk #14 
https://github.com/apache/airflow/blob/master/airflow/models/connection.py#L47
https://github.com/apache/airflow/blob/master/airflow/contrib/hooks/mongo_hook.py
http://docs.mongoengine.org/guide/connecting.html
https://github.com/MongoEngine/mongoengine/blob/master/mongoengine/connection.py
=> Adiciona a capacidade de registrarmos a conexão do OPAC no modelo airflow.models.Connection

airflow/dags/kernel_changes.py
Marca os periódicos como despublicados.
Veja: 
opac_conn: 
kernel_conn:
tk #10 
Não ha.
=> Marcar os periódico como despublicados

airflow/dags/kernel_changes.py
Marca os fascículos como despublicados.
Veja: 
opac_conn: 
kernel_conn:
tk #9 
Não ha.
=> Marcar os fascículos como despublicados

airflow/dags/kernel_changes.py
Adiciona a ordem nos fascículos.
airflow/dags/kernel_changes.py:register_issues
```python
make dev_compose_up
```
Adiciona a ordem do fascículo conforme a posição na lista de fascículos.
tk #28 
Não há.
=> Adiciona a ordem nos fascículos

airflow/dags/kernel_changes.py
Adiciona os campos: 
```
issue_count = IntField()
last_issue = EmbeddedDocumentField(LastIssue)
mission = EmbeddedDocumentListField(Mission)
study_areas = ListField(field=StringField())
sponsors = ListField(field=StringField())
editor_email = EmailField()
```
Para a revisão desse PR é possível verificar as alterações no módulo: **airflow/dags/kernel_changes.py**
Executando o container de desenvolvimento através do commando: make dev_compose_up
Ainda não foi possível adicionar todos os campos por hora, adicionamos o ticket no repositório do kernel: https://github.com/scieloorg/document-store/issues/147
Não há. 
https://github.com/scieloorg/opac-airflow/issues/25
Não há.
=> Adiciona mais alguns campos faltantes na entidade Journal.

airflow/dags/kernel_changes.py
Adiciona a capacidade de cadastrar documento orfãos.
É possível revisar esse PR verificando no seguinte módulo: 
- airflow/dags/kernel_changes.py. 
Executando manualmente o opac-arflow.
A motivação desse PR está relacionado com a necessidade de podermos cadastrar artigo cientifico, sem necessariamente de ter um fascículo relacionado.
Não há.
tk #38 
Não há.
=> Adiciona a capacidade de cadastrar documentos orfãos

airflow/dags/kernel_documents.py, airflow/tests/test_kernel_documents.py
Altera a obtenção do pacotes SPS p/ ler Scilista de arquivo. Antes da alteração estava recebendo uma lista como parâmetros mas decidimos que ler do arquivo `scilista.lst` seria melhor. Este arquivo será lido de path configurado no Airflow, que deve ser acessível pelo servidor onde a aplicação rodar.
Em `airflow/dags/kernel_documents.py`
`docker-compose -f docker-compose-dev.yml exec opac-airflow python -m unittest discover -v`
OU
- Configurando as variáveis:
* `SCILISTA_FILE_PATH`: caminho do arquivo `scilista.lst`
* `XC_SPS_PACKAGES_DIR`: diretório com pacotes SPS (.zips)
* `PROC_SPS_PACKAGES_DIR `: diretório de processamento
Ao executar a DAG, os pacotes determinados na scilista devem ter sido movidos de `XC_SPS_PACKAGES_DIR` para `PROC_SPS_PACKAGES_DIR` …
=> Altera a obtenção do pacotes SPS p/ ler Scilista de arquivo

airflow/dags/kernel_documents.py, airflow/tests/test_kernel_documents.py
Implementa a leitura dos XML dos pacotes SPS listados na tarefa `list_documents` e cria duas listas: uma com os SciELO IDs de documentos para deletar e outra de documentos para manter. Os documentos para deleção são deletados do Kernel na tarefa de deleção.
Também foram feitos ajustes no `list_documents` para entregar os pacotes SPS e seus respectivos XMLs
Em `airflow/dags/kernel_documents.py`, no callable Python `read_xmls`.
`docker-compose -f docker-compose-dev.yml exec opac-airflow python -m unittest discover -v`
OU
- Criando pacote SPS e scilista em diretórios locais e configurando as variáveis pela interface do airflow:
* `SCILISTA_FILE_PATH`: caminho do arquivo `scilista.lst`
* `XC_SPS_PACKAGES_DIR`: diretório com pacotes SPS (.zips)
* …
=> Adiciona deleção de documentos do Kernel

airflow/dags/kernel_gate.py
Este PR adiciona o conceito de pastas temporárias de trabalho onde os insumos de dados como por ex bases MST, arquivos JSON, viverão durante o período de vida do processo.
- `airflow/dags/kernel_gate.py` L: `368`
Para testar manualmente este PR deve-se:
- Configurar a variável `BASE_TITLE_FOLDER_PATH` para a pasta que contenha a base issue, ex: `/usr/local/airflow/bases/scl/title`;
- Configurar a variável `BASE_ISSUE_FOLDER_PATH` para a pasta que contenha a base issue, ex: `/usr/local/airflow/bases/scl/issue`;
- Configurar a variável `WORK_FOLDER_PATH` para a pasta de trabalho temporária ex ` /usr/local/airflow/work/ `
- Inicie a DAG;
- Observe a criação as pastas de trabalho e pastas de execução com a data e hora relativas ao horário de execução da DAG;
- O processo de espelhamento deve …
=> Adiciona conceito de pastas temporárias de trabalho

airflow/.coveragerc, airflow/Dockerfile, airflow/Dockerfile-dev, airflow/dags/common/hooks.py, airflow/dags/common/sps_package.py, airflow/dags/operations/docs_utils.py, airflow/dags/operations/exceptions.py, airflow/dags/operations/sync_documents_to_kernel_operations.py, airflow/dags/sync_documents_to_kernel.py, airflow/tests/fixtures/__init__.py, airflow/tests/test_docs_utils.py, airflow/tests/test_sync_documents_to_kernel.py, airflow/tests/test_sync_documents_to_kernel_operations.py
Implementa `register_update_documents`, função responsável por registrar/atualizar documentos no Kernel e persistir o XMLs, seus ativos digitais e manifestações no Minio.
É realizado em cada pacote SPS:
- Leitura e persistência no Minio dos XMLs a serem persistidos, além da extração de metadados
- Extração e persistência no Minio dos ativos digitais e manifestações de cada um dos XMLs
- Registro/atualização dos documentos no Kernel
- Registro das manifestações dos documentos no Kernel
Este PR também inclui:
- configurações do Coverage
- instalação da biblioteca do S3 no Airflow para conexão com o Minio
- utilização do módulo `sps_package.py` do projeto `document-store-migração`, adaptado para esta aplicação
Em `airflow/dags/operations/sync_documents_to_kernel_operations.py`: função que …
=> Adiciona registro/atualização de documentos no Minio e Kernel

airflow/dags/operations/docs_utils.py, airflow/tests/test_docs_utils.py
Esse PR adição um mecanismo de geração de hash para o filename com base no conteúdo do arquivo.
**Explicação**
Para a geração do hash, a ideia foi usar os primeiros 1024 bytes do arquivo e assim gerar um sha1, e essa estratégia é a mesma utilizada no utilitario de migração `document-store-migracao`
Abaixo segue o comentario que motivou essa implementação
>Essa implementação pode potencialmente consumir muita memória, uma vez que ela lê todo o conteúdo do arquivo em memória de uma vez para calcular a soma. Sugiro fazer algo mais econômico como:
> ```python
>def sha1(path):
>    _sum = hashlib.sha1()
>    with open(path, 'rb') as file:
>        while True:
>            chunk = file.read(1024)
>            if not chunk:
>                break
>            _sum.update(chunk)
>    return …
```
=>  Evitar duplicidade de conteúdo no Object Store

airflow/dags/common/sps_package.py, airflow/dags/operations/docs_utils.py, airflow/dags/operations/sync_documents_to_kernel_operations.py, airflow/dags/pre_sync_documents_to_kernel.py, airflow/tests/fixtures/__init__.py, airflow/tests/test_docs_utils.py, airflow/tests/test_sync_documents_to_kernel_operations.py
Ajustes para o funcionamento da tarefa de relacionamento dos documentos com os _Documents Bundles_:
- Inclui `year` nos metadados obtidos do XMLs
- Retorna nos metadados do XMLs `volume`, `number` e `supplement` somente se eles forem diferentes de nulo
- `register_update_documents` retorna lista com os metadados dos documentos sincronizados com o Kernel para o relacionamento dos documentos com os bundles
Em `airflow/dags/operations/docs_utils.py`, para as alterações nos metadados
Em `airflow/dags/operations/sync_documents_to_kernel_operations.py`, para o retorno da lista de documentos
`docker-compose -f docker-compose-dev.yml exec opac-airflow python -m unittest -v`
OU
- Criando pacote SPS e scilista em diretórios locais e configurando as variáveis pela …
=> Altera obtenção de metadados do XMLs e retorno de tarefa

airflow/dags/kernel_changes.py
Este PR altera o callable da tarefa `register_issues_task`, adequando a leitura dos dados de relacionamento de fascículos com periódicos, que foram alterados no _Kernel_. Assim, é possível registrar os fascículos em seus respectivos periódicos corretamente no OPAC.
Também foram corrigidos o parser de endpoints dos registros de mudança, `JournalFactory` por conta de email do editor e duplicação nos registros de fascículos órfãos.
É recomendado que a revisão seja feita por commit.
- Com registros de relacionamentos entre fascículos e periódicos atualizados com os dados novos no _Kernel_, executar a DAG `kernel_changes`
- Após a execução da task `register_issues_task`, os fascículos devem ser cadastrados com sucesso no OPAC
Os fascículos estão sendo registrados como "regular" no OPAC e, por …
=> Adequa relacionamento de fascículo com periódico

airflow/dags/common/hooks.py, airflow/dags/kernel_gate.py, airflow/tests/test_kernel_gate.py
Esse PR altera o _callable_ da tarefa `link_journals_and_issues_task`. Ao invés do ID do fascículo, agora o relacionamento de cada fascículo com o periódico recebe também o ano de publicação, volume, número, suplemento e ordem/número sequencial. Como a ordem não é mais determinada pela lista no periódico, os dados de cada fascículo são somente adicionados ao final da lista.
Também foram feitos ajustes para que essa tarefa fosse concluída:
- Correção de dados do periódico
- Alteração no envio dos dados para o Kernel
É recomendado que a revisão seja feita por commit.
- Executar a DAG `kernel_gate` completa
- Verificar no _Kernel_ o conteúdo do campo `items` no periódico
- Deve conter os dados do fascículo, não somente o ID
Detalhes no ticket #89 
N/A
#89 
Nenhuma.
=> Altera dados do relacionamento entre periódico e fascículos

airflow/dags/common/hooks.py, airflow/dags/kernel_changes.py, airflow/dags/operations/kernel_changes_operations.py, airflow/tests/fixtures/kernel-document-front-s1518-8787.2019053000621.json, airflow/tests/test_kernel_changes.py
Este pull request adapta o a leitura dos relacionamentos do Kernel.
- `airflow/dags/kernel_changes.py` L `413`
- Baixar o PR;
- Executar o espelhamento a partir de uma base zerada;
- Registrar no Kernel
- Periódicos, fascículos e documentos
- Relacionar as entidades;
- Mediante ao [bug](https://github.com/scieloorg/opac-airflow/issues/95) o relacionamento entre Issue e Document pode não ocorrer, utilize o `curl` para realizar o relacionamento manualmente se preciso for.
- Verificar a leitura dos dados
- Verificar o registro dos documentos na base do OPAC
N/A
N/A
closes #80 
N/A
=> Adequar relacionamento de bundle e documentos às mudanças do Kernel

airflow/dags/kernel_gate.py, airflow/dags/operations/docs_utils.py, airflow/dags/operations/exceptions.py, airflow/dags/operations/sync_documents_to_kernel_operations.py, airflow/dags/sync_documents_to_kernel.py, airflow/tests/test_docs_utils.py, airflow/tests/test_kernel_gate.py, airflow/tests/test_sync_documents_to_kernel.py, airflow/tests/test_sync_documents_to_kernel_operations.py
Este PR cria um índice de ISSNs de periódicos e utiliza-o para obter o ID de bundles para efetuar o relacionamento de documentos com os `DocumentsBundles`. Para isso:
- Na execução da tarefa `process_journals`, cria um arquivo JSON contendo índice contendo todos os ISSNs registrados na `title`, mapeando para o ISSN ID correspondente.
- Altera a tarefa de relacionamento de documentos com _bundles_ para ler e usar o índice de ISSNs de periódicos para formar o ID do fascículo com o ISSN ID ao invés do ISSN do documento.
É recomendado que a revisão seja feita por commits.
1. Execute a DAG de espelhamento e verifique na task `process_journals_task`:
* A criação de um arquivo JSON chamado `issn_index.json` no mesmo diretório que os outros JSONs do espelhamento foram gravados. Este deve conter …
=> Cria índice de ISSNs e utiliza-o no relacionamento de documentos com bundles

airflow/dags/kernel_changes.py, airflow/dags/operations/kernel_changes_operations.py, airflow/tests/test_kernel_changes.py
Este pull request adiciona o suporte ao registro de manifestações de documentos na base do OPAC.
- `airflow/dags/kernel_changes.py` L `234`
Para testar este pull request manualmente deve-se:
- Realize o espelhamento das bases title e issue;
- Inicie o pré sync de pacotes;
- Verifique se os documentos e suas manifestações foram cadastradas com sucesso;
N/A
N/A
#41 
N/A
[rsp_v53_1.zip](https://github.com/scieloorg/opac-airflow/files/3605629/rsp_v53_1.zip)
=> Adiciona suporte de registro para as manifestações de documentos na base do OPAC

Dockerfile, README.md, proc/GeraPadrao.bat, proc/InitKernelGate.bat
O `GeraPadrao` passa a chamar o script `InitKernelGate`, responsável por executar requisição HTTP para iniciar a DAG `kernel-gate` no OPAC-Airflow. Tanto este `GeraPadrao` como o `InitKernelGate` devem ser atualizados/copiados para o diretório `proc` do servidor onde ele é executado.
Em `proc/GeraPadrao.bat`, que foi copiado do projeto https://github.com/scieloorg/Web
- Configurar variável `AIRFLOW_HOST` no script `InitKernelGate.bat` com o servidor do opac-airflow
- No Docker container, executar o script `/usr/local/proc/GeraPadrao.bat`
- Verificar se o script `InitKernelGate.bat` é executado
- Verificar se a DAG é executada no opac-airflow
Nenhum.
N/A.
scieloorg/gera-padrao/issues/1
Nenhuma.
=> Altera GeraPadrao p/ iniciar o Kernel Gate

airflow/dags/operations/kernel_changes_operations.py, airflow/tests/test_kernel_changes.py
Este pull request adiciona o campo `htmls` a sincronização dos artigos com o OPAC. O campo `htmls` é importante (por enquanto) para mantermos a compatibilidade entre a versão que hoje está em produção (scielo.br/scielosp) e a versão usada pra testes com o publishing framework.
- `airflow/dags/operations/kernel_changes_operations.py` L: `229`
Para testar este pull request deve-se:
- Realizar a sincronização da base ISIS;
- Realizar a sincronização de um pacote SPS [anexo 1];
- Verificar o acesso aos artigos e seus pdfs.
O acesso ao artigo ou ao seu pdf pode não funcionar de acordo com a configuração das URLS do SSM (nosso minio/kernel). Precisei alterar alguns trechos de código no arquivo `views.py` do OPAC.
**Linha 1060**
```python
resource_ssm_full_url = resource_ssm_media_path 
``` …
=> Adiciona campo htmls a sincronização com o OPAC

.travis.yml, Dockerfile, airflow/airflow.cfg, docker-compose-dev.yml, docker-compose.yml, entrypoint.sh, start_airflow.sh
Adiciona os ajustes necessários para utilizarmos o **Postgres** como banco de dados. 
Para revisar esse PR é necessário verificar os seguintes arquivos:
* Dockerfile
* ariflow.cfg
* docker-compose-dev.yml
* docker-compose.yml
Para realizar o teste é necessário reconstruir a imagem do docker, seguindo os seguintes passos:
```docker-compose -f docker-compose-dev.yml build``` 
```docker-compose -f docker-compose-dev.yml up -d```
Acessar o admin do airflow: http://localhost:8080
Seguir os mesmos comandos para o arquivo ```docker-compose.yml```
No arquivo de docker-compose-dev.yml, foi adicionado o adminer uma interface web para visualizar banco de dados. 
Para ter acesso a esse interface: http://localhost:8081
=> Adiciona a capacidade de utilizar o postgres como banco de dados.

airflow/dags/kernel_changes.py
Este PR corrige um bug no registro de última issue na `DAG` `Kernel_changes`.
- `airflow/dags/kernel_changes.py` L `735`
1. **Primeiro caso de teste (reproduzindo o bug)**:
- Crie um journal na API do Kernel via cURL:
```shell
curl -X PUT -H 'Accept: application/json' -H 'Content-Type: application/json' http://0.0.0.0:6543/journals/journal-teste -d '{"title": "Exemplo de journal", "acronym": "edj"}' -v
```
- Crie dois bundles via cURL:
```shell
curl -X PUT -H 'Accept: application/json' -H 'Content-Type: application/json' http://0.0.0.0:6543/bundles/journal-teste-2019-v1-n1 -d '{"volume": "1", "number": "1", "publication_year": "2019"}' -v
curl -X PUT -H 'Accept: application/json' -H 'Content-Type: application/json' …
```
=> Corrige bug no registro de última issue

Dockerfile, airflow/dags/sync_isis_to_kernel.py, airflow/dags/sync_kernel_to_website.py, airflow/tests/test_kernel_changes.py, airflow/tests/test_kernel_gate.py, requirements.txt
Este pull request altera os nomes das DAGS de `kernel-gate` e `kernel_changes`, também adiciona um arquivo de `requirements.txt`.
- `Dockerfile` L: `17`
- `airflow/dags/sync_isis_to_kernel.py` L:`82`
- `airflow/dags/sync_kernel_to_website.py` L: `52`
- Executar uma nova instância do airflow com Docker realizando um novo processo de build;
- Executar uma nova instância do airflow sem o uso de Docker;
- O airflow deve funcionar normalmente.
N/A
N/A
#107
N/A
=> Renomeia dags e adiciona arquivo de dependências Python

airflow/dags/operations/kernel_changes_operations.py, airflow/dags/sync_documents_to_kernel.py, airflow/dags/sync_kernel_to_website.py, airflow/tests/test_kernel_changes.py, airflow/tests/test_sync_documents_to_kernel.py, proc/GeraPadrao.bat, proc/SyncIsisToKernel.bat
Este pull request corrige erros gerais detectados no processamento de testes no dia 17/10/2019. Inicialmente a solução foi concentrada na utilização do `scielo-id` de forma correta durante a sincronização do `kernel` com a base do `website`, a estratégia adotada anteriormente utilizava do campo `article_publisher_id` retornado pelo `/front` da API para capturar  o `scielo-id` dos documentos processados e isso se provou extremamente errado uma vez que nós não temos a garantia que este campo retornará o `scielo-id` do documento.
O PR escalou para consertar problemas de sincronização de documentos nas situações de atualização sem registros de mudanças dos `bundles` relacionados com os documentos (passos detalhados no commit 321e276. Também foram feitas melhorias nas mensagens de erro …
=> Corrige pequenos bugs na sincronização entre o Kernel e o Website

airflow/dags/operations/docs_utils.py, airflow/dags/operations/sync_documents_to_kernel_operations.py, airflow/dags/sync_documents_to_kernel.py, airflow/dags/sync_isis_to_kernel.py, airflow/tests/test_docs_utils.py, airflow/tests/test_sync_documents_to_kernel.py, airflow/tests/test_sync_documents_to_kernel_operations.py
Este PR inclui o tratamento de pacotes Ahead of Print no fluxo de sincronização de documentos.
Na prática, a única diferença entre a sincronização de pacotes de fascículos regulares é que o bundle de Ahead of Print pode não existir no momento em que os documentos estão sendo incluídos no Kernel. Diferentemente dos fascículos regulares, que são espelhados para o Kernel antes da sincronização dos documentos, os bundles de AOP, caso não existam, precisam ser criados e vinculados ao periódico de publicação dos documentos antes do relacionamento dos documentos. Assim, é verificado se o pacote a ser sincronizado contém documentos AOP, verifica a existência do bundle de Ahead of Print e, caso não exista, trata de criá-lo adequadamente.
Em …
=> Inclui tratamento de pacotes Ahead of Print no fluxo de sincronização de documentos

airflow/dags/common/sps_package.py, airflow/dags/operations/docs_utils.py, airflow/tests/fixtures/__init__.py, airflow/tests/test_docs_utils.py
Este pull request altera a classe SPS_Package para detectar a versão correta (v3) do
scielo-id (no método `scielo_id`).
- `airflow/dags/common/sps_package.py` L: `85`
- `airflow/dags/common/sps_package.py` L:  `325`
- Baixar o pacote sps [1]; 
- Configurar a scilista para processar o pacote [1];
- Executar a dag de `pre_sync_documents_to_kernel`;
- Verificar que os documentos que possuem o `scielo-v3` foram cadastrados com sucesso;
A partir deste ponto as dags que processam os documentos não entendem o `specific-use="scielo"` sendo assim os pacotes antigos gerados pelo `xc` ou `ds_migracao` não funcionarão.
N/A
closes #130
N/A
[[1] - 6935_rbpv_2019nahead.zip](https://github.com/scieloorg/opac-airflow/files/3893293/6935_rbpv_2019nahead.zip)
=> Seta o scielo-id na versão v3 durante a sincronização de documentos

airflow/dags/sync_kernel_to_website.py
Esse PR tem com objetivo obter os aheads of prints do Kernel e cadastra-los no site
airflow/dags/sync_kernel_to_website.py
Para que seja testado manualmente é necessário que esteja funcionando os seguinte sistemas: **opac**, **opac-airflow** e **kernel**.
Para realizar um cadastro de conteúdo mínino para teste manual segue: 
Cadastro de um Periódico: 
```shell
curl -X PUT -H 'Accept: application/json' -H 'Content-Type: application/json' http://0.0.0.0:6543/journals/0066-782XX -d '{"_id": "0044-5967", "id": "0044-5967", "created": "2019-10-23T17:31:27.442021Z", "updated": "2019-10-23T17:40:12.532839Z", "title": "Acta Amazonica", "mission": [{"language": "es", "value": "Publicar trabajos cient\u00edficos originales sobre Amazonia. "}, {"language": "pt", "value": "Publicar trabalhos …
```
=> Adiciona a capacidade de identificar os ahead of print no momento de cadastro dos fasciculos

airflow/dags/common/hooks.py, airflow/dags/operations/docs_utils.py, airflow/dags/operations/exceptions.py, airflow/dags/operations/sync_documents_to_kernel_operations.py, airflow/dags/operations/sync_kernel_to_website_operations.py, airflow/tests/test_docs_utils.py, airflow/tests/test_sync_documents_to_kernel_operations.py, airflow/tests/test_sync_kernel_to_website.py
Adiciona o tratamento de ex-Ahead of Prints desde o fluxo de ingestão direta até a atualização do site. Executando as DAGs `sync_documents_to_kernel` e `sync_kernel_to_website`, deve:
- atualizar o documento no Kernel
- atualizar o bundle do fascículo regular com o documento ex-AOP no Kernel
- atualizar o bundle de AOP para a retirada do documento em AOP no Kernel
- atualizar o artigo no OPAC, com os `url_segment`s do documento em AOP
- inserir o artigo no fascículo regular
- retirar o artigo do ahead of print
É recomendado que a revisão seja feita por commits ou que inicie pelo arquivo `airflow/dags/operations/sync_documents_to_kernel_operations.py`, L269
- Execute as DAGs `sync_documents_to_kernel` e `sync_kernel_to_website` com um pacote SPS contendo AOPs ou selecione um documento AOP …
=> Adiciona tratamento de ex-Ahead of Prints na sincronização dos documentos e site

airflow/dags/operations/docs_utils.py, airflow/dags/operations/exceptions.py, airflow/dags/operations/sync_documents_to_kernel_operations.py, airflow/tests/test_docs_utils.py, airflow/tests/test_sync_documents_to_kernel_operations.py
Esse PR garante que não seja cadastrado XMLs e asset sem **scielo_id**.
airflow/dags/operations/docs_utils.py
airflow/dags/operations/exceptions.py
airflow/dags/operations/sync_documents_to_kernel_operations.py
airflow/tests/test_docs_utils.py
airflow/tests/test_sync_documents_to_kernel_operations.py
Para testar manualmente é necessário as seguintes instâncias rodando: 
- opac-airflow
- kernel
- minio
Utiliza o pacote: 
[7665_ag_2019nahead.zip](https://github.com/scieloorg/opac-airflow/files/3903036/7665_ag_2019nahead.zip)
Rodar a dag: pre_sync_documents_to_kernel, verificar que a dag: sync_documents_to_kernel também é executada 
O resultado será uma linha no log do ariflow informando que o XML não pode ser depositado, pois não pode obter o **scielo id v3**.
Estamos levantando uma exceção …
=> Garante que não seja cadastrado XMLs e asset sem scielo_id

airflow/dags/operations/sync_kernel_to_website_operations.py, airflow/dags/sync_kernel_to_website.py
Corrige problemas no processamento de sincronização `Kernel -> Website` onde documentos deletados e marcados para deleção quebram a execução das tasks de `registro de documentos`  e `deleção de documentos`.
Os problemas ocorrem quando numa mesma leitura da API de mudanças nós temos:
1) Documento `X` registrado no Kernel mas não registrado no `Website` (ex: às 00:00);
2) Documento `X` removido no Kernel (ex: às 00:01);
3) A task de registro não conseguirá acessar o `/front` do documento que não existe mais no `kernel` já que ele foi removido às `00:01`;
- `airflow/dags/sync_kernel_to_website.py` L: `116`
- `airflow/dags/operations/sync_kernel_to_website_operations.py` L: `304`
- Registrar um novo documento no Kernel;
- Remover o documento do Kernel; …
=> Corrige registro e deleção de documentos durante sincronia do Website

airflow/dags/sync_kernel_to_website.py
Este pull request corrige a segmentação incorreta de issues órfãs. Quando as mudanças de `DocumentBundle` no `Kernel` não acompanham mudanças de `Journal` a task de registro de issue estava automáticamente determinando que os `bundles` eram órfãs o que não necessariamente é verdade já que a operação pode ser um `update parcial`.
- `airflow/dags/sync_kernel_to_website.py` L: `488`
Para testar este pr manualmente deve-se:
- Atualizar um bundle no `kernel` que já esteja cadastrado no `opac`;
- Verificar que o bundle não foi classificado como órfã.
N/A
N/A
closes #126 
N/A
=> Corrige a segmentação incorreta de issues órfãs durante a sincronia do Website

airflow/dags/operations/docs_utils.py, airflow/dags/operations/sync_documents_to_kernel_operations.py, airflow/dags/sync_documents_to_kernel.py, airflow/tests/test_docs_utils.py, airflow/tests/test_sync_documents_to_kernel_operations.py
Este PR corrige a marcação dos documentos sem `scielo-id` para deleção que estavam seguindo como documentos a preservar. Foi alterada a forma como os documentos para deleção são informados na leitura dos dados do XML e, independentemente do documento ter ou não o
`scielo-id`, ele é informado como um documento para deleção e, assim, é possível retirá-lo da lista dos documentos a serem preservados.
Também foram feitas melhorias na execução das tarefas da DAG de sincronização: a otimização da execução das tarefas e o log da entrada de documentos ex-Ahead of Prints.
É recomendado que a revisão seja feita por commits.
Tendo o Airflow configurado:
- Sincronize um pacote SPS contendo documentos para deleção (com `<article-id specific-use="delete">`) e que não tenham `scielo-v3`
- A mensagem de …
=> Corrige marcação dos documentos sem scielo-id para deleção

airflow/dags/operations/sync_kernel_to_website_operations.py, airflow/tests/fixtures/kernel-document-front-s1518-8787.2019053000621.json, airflow/tests/test_sync_kernel_to_website.py
Atribui valores de `scielo_pid_v1`, `scielo_pid_v2` e `scielo_pid_v3`, retornados no `front` de documentos do Kernel, a campo `scielo_pids` do Opac_Schema na sincronização dos documentos do Kernel para o site.
Em `airflow/tests/test_sync_kernel_to_website.py`, para entender o resultado esperado no registro do OPAC.
- Sincronize um novo pacote SPS para o Kernel ou garanta que há documentos com o `/front` retornando `<article-id specific-use="scielo-vn">`
- Execute a DAG `sync_kernel_to_website`
- Verifique o resultado na coleção `article` na base MongoDB OPAC dos documentos sincronizados para o site. Deve existir um campo chamado `scielo_pids` com a mesma estrutura do teste unitário.
Este PR altera somente o OPAC-Airflow e não garante a atualização do OPAC e, por isso, quebra o site que …
=> Atribui valores de SciELO PIDs no sync de documentos do Kernel p/ o site

airflow/dags/common/hooks.py
Depois de alguns testes, foi detectado que algumas respostas às requisições HTTP ao Kernel demoraram mais que 1 segundo, timeout configurado anteriormente e, para garantir uma maior probabilidade das respostas chegarem, o timeout para o tempo de resposta foi aumentado para 10 segundos.
Em `airflow/dags/common/hooks.py`.
- Execute alguma requisição ao Kernel que leva mais de 1 segundo, através da execução de alguma DAG que conecta com o Kernel.
- A execução da DAG deve finalizar com sucesso.
Este problema foi detectado durante os testes de sincronização dos pacotes SPS no servidor de testes.
N/A
N/A.
Nenhuma.
=> Aumenta timeout padrão da conexão com o Kernel

airflow/dags/sync_isis_to_kernel.py, airflow/dags/sync_kernel_to_website.py
Este pull request corrige pequenos bugs durante a sincronização entre o `Kernel->Website` e `Isis->Kernel`.
- `airflow/dags/sync_isis_to_kernel.py` L: `152`
- `airflow/dags/sync_kernel_to_website.py` L: `411`
- **Primeiro caso**:
- Execute a sincronização `isis_to_kernel`;
- Verifique que os `journals` foram cadastrados com sucesso;
- Execute novamente a sincronização `isis_to_kernel`;
- Verifique que não foram enviados `PATCH` massivamente durante a task `process_journals`;
- **Segundo caso**:
- Execute todo o stack de sincronização do `opac-airflow`;
- Atualize um `bundle` do tipo `aop` (pode ser qualquer dado):
- ex: `curl -X PATCH -H 'Accept: application/json' -H 'Content-Type: application/json' …
=> Corrige pequenos bugs durente a execução das dags de sincronização 

airflow/dags/common/hooks.py, airflow/dags/operations/docs_utils.py, airflow/dags/operations/sync_kernel_to_website_operations.py, airflow/tests/test_docs_utils.py, airflow/tests/test_sync_kernel_to_website.py
Este PR altera os seguintes pontos:
- `sync_document_to_kernel`: atualiza os metadados do objeto do PDF criado no Object Store (MinIO) com o nome legado do arquivo. Ex: `en_1983-1447-rgenf-40-spe-e20180114.pdf`
- `sync_kernel_to_website`: obtém os metadados dos objetos PDF do Object Store para armazenar junto com os metadados de PDFs nos documentos de artigo do site novo.
É recomendado que a revisão seja feita por commits.
- Obtenha um pacote SPS com documentos que tenham manifestações PDF em mais de um idioma
- Com a syncronização do ISIS -> Kernel feita, sincronize o pacote SPS
- Sincronize o Kernel -> website
- Ao final, é esperado que o documento na coleção `article` do MongoDB do site esteja com o campo `pdfs` contendo uma lista de objetos com seus respectivos nomes legados dos …
=> Registra nome de PDF legado no Object Store e no Website

airflow/dags/sync_isis_to_kernel.py, airflow/tests/test_sync_isis_to_kernel.py
Este PR altera o espelhamento do ISIS para o Kernel dos fascículos. Como a base ISIS de `issue` pode não conter o SciELO PID dos fascículos, não é possível simplesmente obtê-lo através do acesso aos dados da base via Xylose. Pelo fato de ser possível gerar o PID com os dados que sempre estão presentes na base `issue`, este código altera o preenchimento do campo para envio ao Kernel da forma como o processamento do site faz.
Em `airflow/dags/sync_isis_to_kernel.py`.
- Execute a DAG de espelhamento (`sync_isis_to_kernel`) com as bases ISIS do *serial_proc*.
- A tarefa `process_issues_task` deve ser concluída sem erros
- Os fascículos no Kernel devem estar registrados com o SciELO PID.
Detalhes no ticket: https://github.com/scieloorg/opac-airflow/issues/142#issuecomment-571585147
N/A
#142 …
=> Altera espelhamento ISIS2Kernel para gerar PID dos fascículos

Makefile, airflow/migrations/0001-add-execution-report-tables-202002041716.sql, airflow/migrations/run.py
Adiciona base para registro dos processamentos de documentos via airflow.
N/A
N/A
Não estou seguro sobre o modo de armazenar os arquivos `sql` que esse projeto pode vir a requerer. De toda forma acabei criando uma pasta que deverá conter os arquivos e um script que pode nos ajudar a executar os arquivos sql.
Dessa forma seria possível executar o import dos arquivos a medida que o airflow inicia. Nada impede que importemos esses arquivos na mão.
Nos próximos PRs adicionarei trechos de códigos que detectam se a conexão está configurada e em caso positivo os registros serão armazenados no banco de dados. A ideia por trás é que o processamento funcione independente de salvarmos os logs de execução ou não.
N/A
#77 
N/A
=> Adiciona arquivos base para registar o log de processamento das DAGs

airflow/dags/operations/sync_external_content_to_website_operations.py, airflow/dags/sync_external_content_to_website.py, airflow/tests/fixtures/rss-news-feed.json, airflow/tests/test_sync_external_content_to_website.py, requirements.txt
Este pull request implementa uma nova  DAG responsável por obter as notícias a partir de feeds de notícias (configuráveis via variável do airflow) e registra-las na base de dados do Website.
- `airflow/dags/sync_external_content_to_website.py`
- Configurar a conexão com a base de dados do `website`;
- Executar a dag `sync_external_content_to_website`;
- Verificar se as notícias foram cadastradas na base de dados do website.
É possível configurar o feed de notícias a partir da variável `RSS_NEWS_FEEDS`, é esperado que esta variável contenha um dicionário no formato:
```python
{
"idioma": {
"url": "url do feed"
}
}
```
N/A
#26
N/A
=> Adiciona suporte a sincronização de feeds de notícias com o Website

airflow/dags/operations/sync_external_content_to_website_operations.py, airflow/dags/sync_external_content_to_website.py, airflow/tests/fixtures/rss-press-release-feed.json, airflow/tests/test_sync_external_content_to_website.py
Esse **PR** adiciona a capacidade de coletar os Press Releases do Blog do SciELO. 
Para visualizar as alteração, sugiro os seguintes módulos: 
- airflow/dags/operations/sync_external_content_to_website_operations.py
- airflow/dags/sync_external_content_to_website.py
- airflow/tests/fixtures/rss-press-release-feed.json
- airflow/tests/test_sync_external_content_to_website.py
É possível executando a tarefa pela interface do airflow, vejam: 
Executando os testes, estamos testando um contrutor de Press Releases(PressReleaseBuilder).
Utiliza a seguinte linha de comando para rodar os teste: 
`docker-compose -f docker-compose-dev.yml exec opac-airflow python -m unittest -v`
É importante ter em mente que o acrônimo é a categoria do post que identifica o periódico.
Para essa atividade a fonte dos …
=> TK27 - Task para sincronização do Press Releases

airflow/dags/common/hooks.py, airflow/dags/operations/sync_documents_to_kernel_operations.py, airflow/dags/pre_sync_documents_to_kernel.py, airflow/dags/sync_documents_to_kernel.py, airflow/tests/test_pre_sync_documents_to_kernel.py, airflow/tests/test_sync_documents_to_kernel.py, airflow/tests/test_sync_documents_to_kernel_operations.py
Este pull request permite que a task `delete_documents` da DAG `sync_documents_to_kernel` registre as operações de remoção de artigos. As operações são executadas durante o processamento de pacotes SPS.
- `airflow/dags/common/hooks.py` L: `100`
Para testar manualmente este pr, deve-se:
- Configurar a conexão `postgres_report_connection` no painel de administração do Airflow;
- Executar um processamento com pacotes que contenham documentos para deleção [1];
- Verificar na tabela `xml_documents` se as operações foram registradas como esperado.
Este pull request também sugere um método de implementar os registros das operações. Note que dentro da função que deleta os documentos o código constrói uma lista com informações sobre sucessos e falhas para cada documento processado. O resultado ao …
=> Adiciona log de processamento durante a deleção de documentos

airflow/dags/operations/docs_utils.py, airflow/dags/operations/sync_documents_to_kernel_operations.py, airflow/dags/sync_documents_to_kernel.py, airflow/tests/test_sync_documents_to_kernel.py, airflow/tests/test_sync_documents_to_kernel_operations.py
Este pull request habilita o registro de log para cadastro e atualização de documentos durante a sincronização de pacotes entre o airflow e o Kernel. Também registra os vínculos entre os documentos e os documentbundles.
- c8f127814382f76cff6d8ee11bbd63da4f4f1e5e - `airflow/dags/sync_documents_to_kernel.py` L`87`
- 18bf38fd3ec40d5ccf4441374e66ae4809006db1 - `airflow/dags/sync_documents_to_kernel.py` L`117`
- Crie um pacote SPS com documentos mal formados (sem pid, tags quebradas, etc);
- Crie um pacote SPS com documentos bem formados;
- Registre a conexão `postgres_report_connection` no airflow;
- Crie o banco de dados e importe o sql `airflow/migrations/0001-add-execution-report-tables-202002041716.sql`;
- Execute a primeira …
=> Adiciona log de processamento para registro de documentos e relacionamento de bundles

Dockerfile, README.md, airflow/dags/operations/sync_documents_to_kernel_operations.py, airflow/dags/sync_documents_to_kernel.py, airflow/tests/test_sync_documents_to_kernel.py, airflow/tests/test_sync_documents_to_kernel_operations.py, entrypoint.sh, requirements.txt
Inclui o passo de otimização de pacotes no fluxo entre "deletar documentos" e "registrar documentos"
por commits
1. Passos pré teste:
- Obtenha um pacote SPS com ativos digitais (imagens) não otimizados [1];
- Obtenha um pacote SPS com ativos digitais já otimizados [2];
- Obtenha um pacote SPS contendo apenas documentos para deleção;
- Crie uma scilista com os dois pacotes obtidos anteriormente;
- Execute a dag `pre_sync_documents_to_kernel`;
- Observe as execuções dos dois pacotes na dag `sync_documents_to_kernel`;
2. Teste com o pacote a ser otimizado:
- Observe que para o pacote não otimizado [1] a task `optimize_package_task_id` é executada e um novo arquivo `zip` é gerado;
- Observe que após o termino da task `optimize_package_task_id`, o caminho para arquivo `zip` gerado é passado …
=> Inclui o passo de otimização de pacotes no fluxo

airflow/dags/sync_kernel_to_website.py, airflow/tests/test_sync_kernel_to_website.py
Este PR adiciona a capacidade de atualização de periódicos já migrados sincronizados do site. Esta necessidade foi detectada por conta da migração de logos dos periódicos mas há outros campos que podem ser alterados via admin do site. Aqui estamos tratando em específico somente a URL do logo, para que não seja sobrescrito em uma futura atualização dos dados do
periódico.
Em `airflow/dags/sync_kernel_to_website.py`.
- Execute o `sync_kernel_to_website`
- Acesse o admin do site e altere a URL do logo de um periódico
- Execute o `sync_kernel_to_website` novamente
- O periódico deve estar com a URL do logo sem alteração
N/A
N/A
https://github.com/scieloorg/document-store-migracao/issues/123
.
=> Adiciona capacidade de atualização de periódicos no sync p/ o site

airflow/dags/sync_kernel_to_website.py
Corrige a atualização do campo `order` dos bundles durante a execução da dag `sync_kernel_to_website`.
- `airflow/dags/sync_kernel_to_website.py` L: `431`
- Crie um journal `curl -X PUT -H 'Accept: application/json' -H 'Content-Type: application/json' http://0.0.0.0:6543/journals/journal-de-teste -d {}`
- Crie um bundle `curl -X PUT -H 'Accept: application/json' -H 'Content-Type: application/json'  http://0.0.0.0:6543/bundles/bundle-de-teste -d '{}'`;
- Relacione o bundle com o journal `curl -X PUT -H 'Accept: application/json' -H 'Content-Type: application/json'  http://0.0.0.0:6543/journals/journal-de-teste/issues -d '[{"id": "bundle-de-teste", "year": "2020", "order": "1"}]'`;
- Execute a dag `sync_kernel_to_website`;
- Verifique que …
=> Corrige erro durante atualização dos bundles no Website

airflow/dags/operations/sync_kernel_to_website_operations.py, airflow/dags/sync_kernel_to_website.py, airflow/tests/fixtures/kernel-issues-0001-3714-1998-v29-n3.json, airflow/tests/test_sync_kernel_to_website.py
Este PR adiciona a atribuição das datas de criação e atualização em metadados sincronizados de Fascículos e Artigos do Kernel para o site.
Também foi corrigida atribuição de período de publicação do fascículo, que foi alterado no Kernel.
Em `airflow/dags/sync_kernel_to_website.py`, L480, na atribuição das datas em fascículos.
1. Execute a DAG `sync_isis_to_kernel`
2. Execute a sincronização de documentos para o Kernel
3. Execute a DAG `sync_kernel_to_website`
4. Verifique os dados da coleção `issue` e `article` na base `opac` do MongoDB. Os campos `created` e `updated` devem estar preenchidos
5. Acesse o `admin` da instância do site novo. Os catálogos `Números` e `Artigo` devem ser acessados sem problema.
Apesar dos campos não serem obrigatórios no OPAC_SCHEMA, são usados hoje na …
=> Atribuição de datas de criação e atualização de Fascículos e Artigos p/ o site

airflow/dags/sync_isis_to_kernel.py
Este pull request implementa o requisito de funcionalidade descrito pela issue #167.
- `airflow/dags/sync_isis_to_kernel.py` L: `536`
- Iniciar a execução da DAG `sync_isis_to_kernel`;
- Observar a execução de `trigger_pre_sync_documents_to_kernel_dag_task` após a task de `link_journals_and_issues_task`;
- Observar que a DAG `pre_sync_documents_to_kernel` foi iniciada;
- SE a SciLISTA possuir pacotes novos, então, a DAG `sync_documents_to_kernel` deve ser executada;
N/A
N/A
closes #167 
- [DAG Run Operator](https://github.com/apache/airflow/blob/master/airflow/operators/dagrun_operator.py)
=> Adiciona operador para iniciar a sincronização de documentos após o espelhamento das bases ISIS

airflow/dags/operations/pre_sync_documents_to_kernel_operations.py, airflow/tests/test_pre_sync_documents_to_kernel_operations.py
Este PR altera leitura de pacotes gerados pelo XC com data e hora no nome. Ao ler a scilista, somente o acrônimo e fascículo serão informados mas a DAG de pré sincronização deverá copiar para o diretório de trabalho do airflow todos os pacotes para os fascículos relacionados na scilista. Também garante que a ordem dos pacotes dos fascículos se mantenham ordenados de acordo com a data e hora do nome.
Em `airflow/dags/operations/pre_sync_documents_to_kernel_operations.py`, L30
Com diretório origem contendo pacotes SPS gerados pelo XC e scilista com pacotes relacionados:
1. Configure o airflow, apontando para o diretório origem, um diretório destino de trabalho e o caminho da scilista
2. Execute a DAG `pre_sync_documents_to_kernel`
3. Verifique se os pacotes de todos os fascículos …
=> Altera pré sync de documentos p/ considerar timestamp em nomes de pacote

airflow/dags/operations/pre_sync_documents_to_kernel_operations.py, airflow/dags/pre_sync_documents_to_kernel.py, airflow/tests/test_pre_sync_documents_to_kernel_operations.py
Este PR altera o operador executado pela DAG `pre_sync_documents_to_kernel` para efetuar a leitura de pacotes listados na `scilista` somente se estiverem sem o comando `del`.
Em `airflow/dags/operations/pre_sync_documents_to_kernel_operations.py`.
1. Com pacotes SPS em diretório configurado em variável `XC_SPS_PACKAGES_DIR`, crie uma `scilista` com algum(ns) pacote(s) acompanhados do comando `del` ao final
2. Execute a DAG `pre_sync_documents_to_kernel`
3. A execução de DAGs sem o comando `del` devem ser iniciadas
4. No log da DAG, não deverá haver leitura de pacotes com comando `del`
N/A
N/A
#56 
.
=> Ignora comando DEL da scilista na pré sincronização de documentos

requirements.txt
Este PR atualiza a versão do Packtools para a última (2.6.4), que corrige problema na leitura do XML.
Em `requirements.txt`
Para instalação em virtualenv, execute `pip install -r requirements.txt`
OU
Para instalação em Docker, recrie o container para instalar a nova versão do Packtools.
Com o Airflow atualizado, tente sincronizar pacotes SPS.
Ocorreu um problema durante os testes do fluxo de ingestão direta utilizando a nova plataforma e não foi possível ler alguns documentos XMLs que apresentaram o seguinte erro na leitura do arquivo: `PCDATA invalid Char value 3, line 1, column ???? (<string>, line 1)`. Estes pacotes foram otimizados para WEB pelo Packtools e, com a versão mais nova, o problema não ocorre.
.
.
.
=> Atualiza versão do Packtools para 2.6.4

airflow/dags/sync_kernel_to_website.py
Este PR altera a sincronização de Bundles do Kernel para o site para que bundles de _Ahead of Print_ não apareçam no site quando não houverem documentos. Para isso, o valor de `Issue.type` precisa ser definido como `outdated_ahead` e, assim, manter compatibilidade com o antigo processamento.
Em `airflow/dags/sync_kernel_to_website.py`
- Adicione um bundle de AOP em um periódico no Kernel
- Sincronize os dados do Kernel para o site
- Observe que na grade de números do periódico no site não aparece o bundle de AOP
- Adicione documentos no bundle de AOP
- Sincronize os dados do Kernel para o site
- Observe que na grade de números do periódico no site aparece o bundle de AOP
- Mova ou remova os documentos do bundle de AOP no Kernel
- Sincronize os dados do Kernel para o site
- Observe que na …
=> [sync_kernel_to_website] Altera tipo de AOP quando não tiver nenhum documento

airflow/dags/operations/sync_isis_to_kernel.py, airflow/dags/sync_isis_to_kernel.py, airflow/tests/test_sync_isis_to_kernel.py
Este pull request corrige o issue #174, fazendo com que durante a sincronização dos periódicos, o campo `status_history` seja persistido/atualizado no Kernel.
- `airflow/dags/sync_isis_to_kernel.py` L`109`
- Inicie uma instância do airflow;
- Configure as conexões/variáveis do airflow;
- Inicie o processo de espelhamento executando a DAG `sync_isis_to_kernel`;
- Observe que o campo `status` deu lugar ao campo `status_history` que agora contém uma lista de status.
N/A
N/A
#174 
N/A
=> Modifica o uso do campo `status_history` ao sincronizar o periódicos

airflow/dags/common/sps_package.py, airflow/tests/test_docs_utils.py
Atualiza o método `number` da classe `SP_Package` de acordo com o código do repositório [ds migração](https://github.com/scieloorg/document-store-migracao/blob/496722f72d2a7ffe1169a9db18b306f0ff5e9258/documentstore_migracao/export/sps_package.py#L349-L360). É possível ver a motivação da modificação [aqui](https://github.com/scieloorg/document-store-migracao/commit/b8c80c8bdfe7c0119b2c7c3f2b2dd15cb53c7d84).
N/A
N/A
N/A
N/A
N/A
N/A
=> Atualiza método da classe SP_Package de acordo com o ds migração

airflow/dags/common/hooks.py
Este pull request corrige o erro de execução da task `sync_documents_to_kernel` quando a conexão com o `Kernel` está parcialmente indisponível, permite que tentativas de conexões sejam feitas.
- `airflow/dags/common/hooks.py`
- Inicie uma instância do airflow;
- Desligue a instância do `Kernel`;
- Execute a DAG de sincronização dos documentos;
- Observe que algumas tentativas de execução serão realizadas;
- A task irá quebrar porque a conexão com o Kernel é requisito básico MAS as tentativas serão realizadas.
N/A
N/A
#182 
- https://airflow.apache.org/docs/stable/concepts.html#jinja-templating
- https://airflow.apache.org/docs/stable/macros-ref.html
=> Define variável HTTP_HOOK_RUN_RETRIES sem templates jinja

airflow/dags/operations/pre_sync_documents_to_kernel_operations.py, airflow/dags/pre_sync_documents_to_kernel.py, airflow/tests/test_pre_sync_documents_to_kernel.py, airflow/tests/test_pre_sync_documents_to_kernel_operations.py, proc/GeraPadrao.bat, proc/PrepSyncToKernel.bat
Este PR garante idempotência na reexecução de DagRun `pre_sync_documentos_to_kernel`, iniciando processo de sincronização dos pacotes sincronizados na primeira execução.
Para garantir que os pacotes serão exatamente os mesmos da execução da DAG, um diretório identificado com o DagRun ID é criado e, dentro dele, são armazenados a scilista inicial do diretório alimentado pelo GeraPadrao, todos os pacotes relacionados aos números da scilista e um arquivo com a relação de todos os paths de pacotes do diretório. Este último é salvo somente caso a movimentação dos arquivos foi feita conforme esperado, ordenada pelo nome dos pacotes.
Em uma reexecução desse DagRun, o ID é o mesmo e é possível identificar o diretório e todo o conteúdo, não sendo necessário refazer as movimentações de arquivos, …
=> Idempotência na reexecução de DagRun `pre_sync_documentos_to_kernel`

proc/PrepSyncToKernel.bat
Este PR tem o objetivo de alterar o script de cópia dos pacotes SPS para o SPF mais robusta e mitigar problemas de instabilidade de rede na movimentação dos pacotes para o SPF. Os parâmetros `-qa` são para ter o comando em modo silencioso e tentar preservar as características do arquivo (mode, owner, group, outros), `--inplace` para atualizar o arquivo no destino, caso já exista, e `--remove-source-files` para remover o arquivo da origem, caso consiga executar o comando com sucesso.
Commit 1d0c7c2
- Crie diretório de origem com arquivos ZIP, simulando o diretório de saída do XC.
Ex:
```
$ ls dir_origem
2020-07-13-16-03-47-785030_acron_v1n2.zip
data_abc_v1n1.zip
data_ag_v42.zip
data_axy_2020nahead.zip
data_csp_v4nspe3.zip
```
- Crie diretório de destino, simulando o diretório do SPF. Ex: …
=> [FASE 3] Substitui comando mv por rsync

airflow/dags/check_website.py, airflow/dags/sync_isis_to_kernel.py, proc/CallGeraUriList.bat, proc/CallTriggerSyncIsisToKernel.bat, proc/GeraPadrao.bat, proc/GeraUriList.bat, proc/SyncToKernel.ini.template, proc/TriggerSyncIsisToKernel.bat
Garante que ao executar a DAG `check_website`, use as `uri_list_<sufixo>.lst` pendentes de verificação.
Garante isso, gerando um `GERAPADRAO_ID` e o passando para todos os scripts vinculados com o `GeraPadrao.bat` de modo que fiquem vinculados: scilista.lst, uri_list.lst e o disparo da DAG `sync_isis_to_kernel`. 
por commits
**Teste da Execução do GeraPadrao**
Teste em um ambiente onde possa executar o `mx`.
1. Crie o diretório `log` em `proc`
2. Crie um arquivo `GeraScielo.bat` vazio
3. Configure o arquivo `proc/SyncToKernel.ini`, use `proc/SyncToKernel.ini.template` como modelo
4. Extraia 
[bases-work.zip](https://github.com/scieloorg/opac-airflow/files/5058707/bases-work.zip) num diretório irmão de `proc`. Nesta base contém dois fascículos (`anaimsp v27` e `anaimsp v28`)
5. Entre no …
=> Garante que ao executar a DAG `check_website`, use todas as `uri_list_<sufixo>.lst` pendentes de verificação

airflow/dags/pre_sync_documents_to_kernel.py, airflow/tests/test_pre_sync_documents_to_kernel.py, proc/CallPrepSyncToKernel.bat, proc/PrepSyncToKernel.bat
Este PR corrige a leitura da `scilista` pela DAG `pre_sync_documents_to_kernel`, que se baseava na data de execução da DAG e que pode acontecer em dia diferente do processamento.
Foi feita alteração no script `PrepSyncToKernel` para receber ID do GeraPadrao, que é utilizado na identificação da `scilista` e dos logs gerados pelo script. Também foi alterada a DAG `pre_sync_documents_to_kernel` para utilizar este ID, armazenado em `Variables`, na leitura da `scilista`. Assim, ao invés da data de execução do DagRun, passa a obter o valor do GeraPadrao ID, usado para identificar a scilista de novos processamentos. Este ID será usado somente caso não exista uma scilista 
associada a esse DagRun, para manter a idempotência da execução.
Commit a5e366d.
Com pacotes em um diretório alimentado pelo …
=> Corrige leitura da scilista gerada pelo script de processamento PrepSyncToKernel

proc/CallPrepSyncToKernel.bat, proc/CallTriggerSyncIsisToKernel.bat, proc/PrepSyncToKernel.bat, proc/TriggerSyncIsisToKernel.bat
Alterar comando `rsync` para resolver o erro que estava ocorrendo:
```
rsync: close failed on "/var/www/scielo_br/spf/": Invalid argument (22)
rsync error: error in file IO (code 11) at receiver.c(859) [receiver=3.1.2]
```
por commits
1. Entre no ambiente de homologação (`/var/www/scielo_br/proc_spf`)
2. Copie pelo menos um pacote de `/var/www/scielo_br/xc_gerapadrao` para  `/var/www/scielo_br/proc_spf/xc_gerapadrao` 
3. Crie uma scilista em `/var/www/scielo_br/proc_spf/`, colocando linhas em branco e pelo menos um acron volumenumero correspondente ao inserido na pasta `/var/www/scielo_br/proc_spf/xc_gerapadrao`
4. Execute o ./PreSyncToKernel.bat, no ambiente de homologação (`/var/www/scielo_br/proc_spf/`)
5. Observe os arquivos gerados em: `/var/www/scielo_br/spf_hml`.
- …
=> [FASE 3] Alterar comando `rsync` para resolver o erro que estava ocorrendo

proc/PrepSyncToKernel.bat
Ajusta `PreSyncToKernel.bat` para evitar manipular a scilista original em concorrência com `GeraScielo.bat`
por commits
1. Tenha o ambiente preparado. 
- Crie diretório de origem com arquivos ZIP, simulando o diretório de saída do XC.
Ex:
```
$ ls dir_origem
2020-07-13-16-03-47-785030_acron_v1n2.zip
2020-07-13-16-03-47-785030_abc_v1n1.zip
2020-07-13-16-03-47-785030_ag_v42.zip
2020-07-13-16-03-47-785030_axy_2020nahead.zip
2020-07-13-16-03-47-785030_csp_v4nspe3.zip
```
- Crie diretório de destino, simulando o diretório do SPF. Ex: `dir_destino`
- Crie `scilista.lst` com conteúdo de fascículos.
```
acron v1n2
abc v1n1
ag v42
csp v4nspe3
```
- Acesse o diretório `proc/`, crie uma cópia do arquivo `SyncToKernel.ini.template` e configure as variáveis `SCILISTA_PATH`, `XC_SPS_PACKAGES` e …
=> [FASE 3][GeraPadrao] Ajusta PreSyncToKernel para evitar manipular a scilista original em concorrência com GeraScielo.bat

airflow/dags/check_website.py, airflow/tests/test_check_website.py, airflow/tests/test_check_website_operations.py
Revisa os tipos de operadores (PythonOperator ou ShortCircuitOperator) e, em consequência os retornos e os pré-requisitos de execução de cada tarefa da DAG `check_website`.
por commits
Ver seção "Como este poderia ser testado manualmente", do #216
- Inicialmente, neste PR, foi pensado que todas as tarefas poderiam ser `ShortCircuitOperator`, mas se uma tarefa é dependente de mais de 1 fluxo, como a `merge_uri_items_from_different_sources_task`, as tarefas das quais ela depende não podem parar, senão ela não é finalizada. 
n/a
closes #211
ler descrição do PR #216
=> Melhorias na DAG `check_website`

proc/CallPrepSyncToKernel.bat, proc/PrepSyncToKernel.bat, proc/SyncToKernel.ini.template
Envia email contendo o PreSyncToKernel.log ao executar GeraPadrao.bat, desde que o email esteja configurado
proc/SyncToKernel.ini.template
proc/CallPrepSyncToKernel.bat
proc/PrepSyncToKernel.bat
1. Tenha o ambiente preparado. 
- Crie diretório de origem com arquivos ZIP (não precisam ser reais), simulando o diretório de saída do XC.
Ex:
```
$ ls dir_origem
2020-07-13-16-03-47-785030_ag_v42.zip
2020-07-13-16-03-47-785030_axy_2020nahead.zip
2020-07-13-16-03-47-785030_csp_v4nspe3.zip
```
- Crie diretório de destino, simulando o diretório do SPF. Ex: `dir_destino`
- Crie `scilista.lst` com conteúdo de fascículos.
```
acron v1n2
abc v1n1
ag v42
csp v4nspe3
```
- Acesse o diretório `proc/`, crie uma cópia do arquivo `SyncToKernel.ini.template` e configure as variáveis `SCILISTA_PATH`, …
=> Caso configurado um email, será enviado o relatório PreSyncToKernel.log

Dockerfile, README.md, requirements.txt
Adiciona o Sentry como uma dependência do projeto em `requirements.txt`. Essa integração foi inserida em versões mais recentes do Airflow e, por isso, também faz-se necessário atualizar a versão dele.
Pelo commit 27a16b8.
- Execute o build para construir a nova imagem Docker do projeto (com `docker-compose build` ou `docker build .`)
- Adicione a variável de ambiente `AIRFLOW__SENTRY__SENTRY_DSN` no `docker-compose.yml` ou declare a variável executando `docker run`. O valor deve ser um DSN válido do Sentry
- Provoque uma exceção no Airflow. Ex: apague uma das variáveis essenciais para a execução de uma DAG e tente rodá-la
- A exceção deve ser enviada para o Sentry
.
.
https://github.com/orgs/scieloorg/projects/4#card-44828419.
https://docs.sentry.io/platforms/python/guides/airflow/
=> Adiciona o Sentry como uma dependência do projeto

airflow/dags/operations/sync_kernel_to_website_operations.py, airflow/tests/test_sync_kernel_to_website.py
Caso o valor de `order` não seja válido (conversível a int), retorna 0.
por commits
Ver #230 
Erro foi causado porque o XML não continha o `<article-id pub-id-type="other"/>` que é obrigatório quando fpage é alfanumérico.
relacionado com https://github.com/scieloorg/document-store-migracao/issues/365
n/a
#230 
n/a
=> Trata o `order` caso seu valor não seja válido (conversível a int)

airflow/dags/sync_documents_to_kernel.py, airflow/dags/sync_isis_to_kernel.py
Este pull request permite que tasks que falharam durante a execução, por qualquer que seja o motivo (ex: _timeout_), possam ser reexecutadas automaticamente pelo _scheduler_ do airflow.
Essa estratégia vai nos garantir mais robustez na hora de executar tarefas que alteram o estado do `kernel` (ex: `sync_documents_to_kernel`), assim,  por exemplo se houve uma falha na hora inserção de um documento, a task será reexecutada por até 5 vezes com um espaço de tempo de 5 minutos entre cada execução.
A partir do commit 4227d35
Para testar este PR manualmente, deve-se:
- Suba uma instância do airflow;
- Desligue algum ponto de integração (minio, kernel);
- Execute a sincronização de um pacote SPS;
- Observe as tasks falharem;
- Observe o _scheduler_ marcar a task como `up_for_retry`;
- Observe que …
=> Adiciona reexecuções para tasks que interagem com Kernel e Minio

airflow/dags/operations/exceptions.py, airflow/dags/operations/sync_kernel_to_website_operations.py, airflow/tests/fixtures/kernel-document-front-s1518-8787.2019053000621_sem_pid_v2.json, airflow/tests/test_sync_kernel_to_website.py
Usa como valor do "order" os 5 últimos dígitos do PID v2 em caso de o `document_order` fornecido ao `ArticleFactory` for inválido
pelo commit 446d24dab5ae7c8493c0f49434164cc613f0b682
Ver #230
n/a
n/a
#230
n/a
=> Usa como valor do "order" os 5 últimos dígitos do PID v2 em caso de o `document_order` fornecido ao `ArticleFactory` for inválido

airflow/dags/operations/check_website_operations.py, airflow/dags/operations/docs_utils.py, airflow/tests/test_check_website_operations.py, airflow/tests/test_docs_utils.py
Evitar a exceção quando não existe o ativo digital no manifest do documento e também apresenta a ausência nos relatórios
por commits
- veja como simular o erro #227
- aplique a DAG check_website do documento mencionado
- verifique que o problema foi corrigido
- no grafana, quando estiver programado, o documento deveria aparecer em "falha em menção de ativos digitais"
n/a
n/a
#227 
n/a
=> Evitar a exceção quando não existe o ativo digital no manifest do documento e também apresenta a ausência nos relatórios

README.md, airflow/dags/common/hooks.py, airflow/dags/sync_kernel_to_website.py
Este PR possibilita a configuração de timeout para as requisições `GET` feitas ao Kernel para a DAG `sync_kernel_to_website`. Também foi alterado o timeout padrão da conexão com o Kernel no módulo `hook`.
Pelo commit 33c4c07 ou módulo `airflow/dags/common/hooks.py`
- Configure um servidor HTTP de teste para simular uma não resposta ou resposta com tempo maior que 13 segundos
- Dispare a DAG `sync_kernel_to_website`
- Verifique se o erro de timeout ocorre e qual o timeout usado no log, como na imagem [1]
- Configure a variável `KERNEL_FETCH_DATA_TIMEOUT` nas variáveis do Airflow com um valor numérico
- Repita o passo 2 e 3
.
[1] - Log do Airflow com ocorrência de timeout na requisição com o Kernel
#239 
.
=> Adiciona configuração para timeout de requisições de consulta com o Kernel

airflow/dags/check_website.py, airflow/dags/operations/check_website_operations.py, airflow/dags/subdags/check_website_subdags.py, airflow/tests/test_check_website.py, airflow/tests/test_check_website_subdag.py
Esta alteração resolve o problema de ter que reprocessar  N documentos devido a uma falha de uma tarefa, fazendo com que tudo fosse reprocessado mesmo que já tivesse passado com sucesso.
A nova abordagem divide em "fascículos" os N documentos de modo que se as tarefas pararem não seja necessário recomeçar a processar desde o início, mas sim apenas aqueles grupos que falharam.
por commits
Crie uma lista contendo PIDs e armazendo em um arquivo teste.csv que vc deve informar na Variable `PID_LIST_CSV_FILE_NAMES`(exemplo: `[ "teste.csv" ]`). Veja o README.
Dispare a DAG check_website.
n/a
DAG check_website
ZOOM
SubDags com falhas
SubDags reexecutadas
#228
n/a
=> Modifica a DAG check_website, nas tarefas relacionadas com verificar os documentos em profundidade

Makefile, airflow/dags/operations/exceptions.py, airflow/dags/subdags/check_website_subdags.py, airflow/dags/subdags/sync_kernel_to_website_subdag.py, airflow/dags/sync_kernel_to_website.py, airflow/tests/test_sync_kernel_to_website.py, airflow/tests/test_sync_kernel_to_website_subdag.py
Substitui as tasks de registro documentos e a de registro de renditions por uma subdag para facilitar em caso de falha, reprocessar apenas os grupos que obtiveram falhas.
por commits
Execute a sincronização do kernel para o website, ou seja, dispare a DAG `sync_kernel_to_website`, mas antes observe o valor da variável `change_timestamp` que indica a data inicial a partir de quando obter as mudanças no kernel (se colocar uma data muito recente poderá não obter nenhum dado)
Os grupos de documentos (ID de documentos) foi feito por _bundle_  pois a tendência é que se o documento de um _bundle_ falhar, possivelmente os demais também. Após a divisão em grupos, para cada grupo é executada a sequência de registro de documentos e depois registro de seus respectivos renditions. 
Poderia ocorrer de …
=> Substitui as tasks de registro documentos e a de registro de renditions por uma subdag

airflow/dags/operations/sync_kernel_to_website_operations.py, airflow/tests/test_sync_kernel_to_website.py
Ajusta a data de publicação do artigo "pub" para um formato esperado pelo site ``yyyy-mm-dd``.
Através módulo: `sync_kernel_to_website_operations.py`
Realizando manualmente a execução da **dag** de sincronização com o site.
`docker-compose -f docker-compose-dev.yml exec opac-airflow python -m unittest -v`
A data é utilizada nos seguintes trechos do site: 
https://github.com/scieloorg/opac/search?q=publication_date
N/A
https://github.com/scieloorg/opac/issues/1665
N/A
=> Ajusta a data de publicação do formato "31 01 2019" para "2019-01-31".

airflow/dags/sync_kernel_to_website.py
Obtém um dos valores do dicionário que tem lista não vazia. Se os itens  da lista forem todos dicionários, é o formato antigo e lança a exceção para que a leitura seja feita de forma adequada. Caso contrário, retorna `(None, {})` pois não foi possível encontrar o PID do documento em `known_documents`, que está no novo formato.
Commit da654ee
1. Insira novos documentos no Kernel
2. Execute a DAG `sync_kernel_to_website`
3. Verifique se a DAG conclui com sucesso
.
N/A
#246 
.
=> Corrige verificação de valores do dicionário known_documents

airflow/dags/operations/docs_utils.py
Troca `lxml.etree.Error` por `etree.XMLSyntaxError`, `etree.Error`
por commits
Veja #250
n/a
n/a
#250
n/a
=> Troca `lxml.etree.Error` por `etree.XMLSyntaxError, etree.Error`

airflow/dags/subdags/sync_kernel_to_website_subdag.py, airflow/tests/test_sync_kernel_to_website_subdag.py
Este PR adiciona retentativa para as tarefas de `register_documents_groups_id_<bundle_id>_docs` e `register_documents_groups_id_<bundle_id>_renditions` da DAG de sincronização do Kernel com o site. Esta tarefa de retentativa está hoje sendo feita manualmente e, muitas vezes, uma retentativa é suficiente para que a tarefa seja executada com sucesso.
Commit efb2745.
1. Certifique-se de ter mudanças de documentos registradas no Kernel que não foram aplicadas à sua instância do site
2. Execute a DAG `sync_kernel_to_website`
3. Simule uma falha na conexão com o Kernel durante a execução da subdag `sync_kernel_to_website.register_documents_groups_id`. Ex: se estiver rodando em Docker, pare o conteiner do Kernel.
4. Espere a subdag `sync_kernel_to_website.register_documents_groups_id` falhar.
5. …
=> Adiciona retentativa em registro de documentos na sincronização do Kernel com o site

airflow/dags/subdags/sync_kernel_to_website_subdag.py, airflow/dags/sync_kernel_to_website.py, airflow/tests/test_sync_kernel_to_website_subdag.py
Na SubDag que registra os documentos e suas manifestações foi inserido um bug que deixa de registrar os órfãos (`orphan_documents` e `orphans_renditions`)
por commits
Registrando em variáveis lista de órfãos e também incluindo para processar na DAG `sync_kernel_to_website` documentos que tenha órfãos (documents e renditions).
Ao final da DAG, verifique os valores de Variable. Os órfãos devem estar registrados em `orphan_documents` e `orphans_renditions`
Este bug foi detectado ao revisar a fim de reduzir o tempo de processamento. (ticket original #248)
n/a
n/a
n/a
=> [sync_kernel_to_website] corrige bug que deixa de registrar os órfãos

airflow/dags/subdags/check_website_subdags.py, airflow/dags/subdags/sync_kernel_to_website_subdag.py, airflow/dags/sync_kernel_to_website.py
Este PR altera o nível do log das mensagens nas funções de criação das SubDags `check_website.check_documents_deeply_grouped_by_issue_pid_v2_id` e `sync_kernel_to_website.register_documents_groups_id`, pois a execução delas está fazendo com que os arquivos de log cresçam muito.
Commit 14de163.
- Certifique-se que o nível de log da aplicação está como o de produção (INFO)
- Suba os serviços do Airflow usando o `docker-compose-dev`
- Verifique os arquivos de log nos caminhos `../airflow/logs/scheduler/2021-01-05/check_website.py.log` e `airflow/logs/scheduler/2021-01-05/sync_kernel_to_website.py.log`
- Observe que as mensagens com o nível alterado pelo PR não são mais registradas
Foram alterados específicamente estes pontos pois são os que estão aumentando mais o volume de logs por conta do …
=> Altera nível de mensagens de log de subdags

airflow/dags/operations/check_website_operations.py, airflow/tests/test_check_website_operations.py
Este PR adiciona análise dos detalhes de HTMLs incompletos para verificar se no nível do documento, com todos os HTMLs, é considerado ou não incompleto. Há casos em que são usados ativos digitais diferentes para cada tradução do texto e apontá-los como ausentes é um problema.
Commit 07c12af.
- Pegue uma amostra do arquivo `homolog-metodologia.scielo.org:/var/www/scielo_br/xc_gerapadrao/airflow-gate/2012-2014_errors_html.csv` e salve no diretório do volume configurado na variável do Airflow `XC_SPS_PACKAGES_DIR`. Inclua o PID `S0103-507X2012000100012`
- Configure as seguites variáveis no Airflow:
- `PID_LIST_CSV_FILE_NAMES` = ["nome-do-arquivo-criado-no-passo-1.csv"]
- `WEBSITE_URL_LIST` = ["https://new.scielo.br"]
- Execute a DAG `check_website` e aguarde que a subdag …
=> Tk-262: Adiciona análise de ativos digitais identificados como ausentes na checagem de HTMLs

airflow/dags/operations/check_website_operations.py
Este PR corrige o PR #264. Se o ativo digital estiver presente em mais de um HTML, a lógica de que há ativos digitais para cada idiomas e quebrada e, por mais que esteja correto, será necessário validar.
Commit ce5abf8.
- Pegue uma amostra do arquivo `homolog-metodologia.scielo.org:/var/www/scielo_br/xc_gerapadrao/airflow-gate/2009_html.csv` e salve no diretório do volume configurado na variável do Airflow `XC_SPS_PACKAGES_DIR`. Confirme que o PID `S0066-782X2009000100006` esteja lá
- Configure as seguites variáveis no Airflow:
- `PID_LIST_CSV_FILE_NAMES` = ["nome-do-arquivo-criado-no-passo-1.csv"]
- `WEBSITE_URL_LIST` = ["https://new.scielo.br"]
- Execute a DAG `check_website` e aguarde que a subdag `check_website.check_documents_deeply_grouped_by_issue_pid_v2_id` seja executada
- Acesse …
=> Corrige check_website na verificação assets não referenciados em HTML

airflow/dags/operations/sync_kernel_to_website_operations.py, airflow/tests/fixtures/kernel-document-front-s1518-8787.2019053000621_previous_pid.json, airflow/tests/test_sync_kernel_to_website.py
Corrige bug de não atualizar os dados de PID se o documento é ex aop.
por commits
Ver #273, a seção como reproduzir
n/a
#273
n/a
=> Corrige bug de não atualizar os dados de PID se o documento é ex aop.

airflow/dags/sync_kernel_to_website.py
Não considerar o ahead como último número ao atualizar o `last_issue` de Journal.
por commits
Executar o sync_kernel_to_website e verificar que nenhum last_issue será ahead.
n/a
```
[2021-05-05 15:31:11,794] {sync_kernel_to_website.py:827} INFO - Novos estud. CEBRAP, 9999 (ahead)
[2021-05-05 15:31:11,798] {sync_kernel_to_website.py:828} INFO - Novos estud. CEBRAP, 2020 39(2)
```
https://github.com/scieloorg/opac/issues/1866
n/a
=> [sync_kernel_to_website] Não considerar o ahead como último número

airflow/dags/common/sps_package.py, airflow/dags/operations/sync_kernel_to_website_operations.py, airflow/dags/sync_kernel_to_website.py, airflow/tests/test_sps_package.py, airflow/tests/test_sync_kernel_to_website.py
Permite que documentos sejam resincronizados no site sem a dependência de estar listados em changes, pois de fato não houve mudança nos dados, mas sim bug na sincronização.
por commits
Incluir pid v3 na lista de orphan_documents e executar o `sync_kernel_to_website`. Verificar no log que há as mensagens."
```
[2021-05-04 21:29:37,391] {sync_kernel_to_website.py:168} INFO - Unable to find QTsr9VQHDd4DL5zqWqkwyjk in bundles changes. Try to get bundle_id and order from Kernel
[2021-05-04 21:29:37,416] {base_hook.py:89} INFO - Using connection to: id: kernel_conn. Host: 192.168.1.19, Port: 6543, Schema: None, Login: None, Password: None, extra: None
[2021-05-04 21:29:37,421] {http_hook.py:136} INFO - Sending 'GET' to url: http://192.168.1.19:6543/bundles/2236-9996-2020-v22-n47
[2021-05-04 …
```
=> Permite que documentos sejam resincronizados no site sem a dependência de estar listados em changes

airflow/dags/sync_kernel_to_website.py, airflow/tests/fixtures/kernel-issues-0001-3714-1998-aop.json, airflow/tests/fixtures/kernel-issues-0001-3714-1998-n3-s0.json, airflow/tests/fixtures/kernel-issues-0001-3714-1998-n3.json, airflow/tests/fixtures/kernel-issues-0001-3714-1998-v29-s0.json, airflow/tests/fixtures/kernel-issues-0001-3714-1998-v29.json, airflow/tests/test_sync_kernel_to_website.py
Conserta a formação do issue.label: quando há volume, prefixar com `v`, se há número prefixar com `n`, se há suplemento prefixar com `s`.
airflow/dags/sync_kernel_to_website.py
Executando a sincronização do kernel com o site, ao registrar fascículos.
Este campo é usado para obter, por exemplo, os pdf com url no formato `/pdf/<acron>/<issue_label>/<filename>.pdf`
n/a
#279 e https://github.com/scieloorg/opac/issues/1921
Ambos relacionados com o problema de ficar inacessíveis os pdfs acessados por este formato de rota: `/pdf/<acron>/<issue_label>/<filename>.pdf`
n/a
=> Conserta a formação do issue.label

airflow/dags/operations/sync_kernel_to_website_operations.py, airflow/tests/test_sync_kernel_to_website.py
Modifica a forma de atualizar e loga os valores de `article.aop_pid` e `article.pid`
por commits
Verificar a informação que ficou logada.
Aparentemente o `article.aop_pid` não foi atualizado mesmo com o PR aplicado anteriormente.
#279
n/a
=> Modifica a forma de atualizar e loga os valores de `article.aop_pid` e `article.pid`

airflow/dags/operations/sync_kernel_to_website_operations.py
Corrige o status do documento para `publicado`. 
O documento fica com o status errado porque a versão anterior entrou no site como "apagado", então o status é `False`.
E ao ingressar no site para ser publicado, o seu status não estava sendo atualizado para `True`. Este PR é para corrigir este defeito.
Por commits
Verificar um documento no site que está como não publicado.
Verificar o documento no kernel que está como publicado, ou seja, que a sua última versão não está "deleted".
Inserir o pid v3 na variável `orphans_documents` e executar a sincronização do kernel com o site.
Verificar que o artigo no site passou a ficar público.
n/a
Indique uma issue ao qual o …
=> Corrige o status do documento para `publicado`

airflow/dags/operations/sync_kernel_to_website_operations.py
Insere em `scielo_pids['other']` também os valores `article_publisher_id` de kernel/front
por commits
Tenha um documento como este
É esperado que na base do opac fique como:
```json
"scielo_pids" : {
"v2" : "S1517-97022021000101203",
"v3" : "89XTbcZcDv5Mb5nfDgQPzMt",
"other": [
"89XTbcZcDv5Mb5nfDgQPzMt",
"S1517-97022021000101203",
"cLqBPgzjH6PBjKPWxBZzn9L"
],
}
```
n/a
n/a
problemas de artigos não disponíveis
n/a
=> Insere em `scielo_pids['other']` também os valores `article_publisher_id` de kernel/front

airflow/dags/operations/sync_kernel_to_website_operations.py, airflow/tests/test_sync_kernel_to_website.py
Esse PR corrigi um erro adicionado na tag final v1.0.0-rc33
Por commit.
Necessário um ambiente completo do opac-airflow para teste manual.
Indico somente rodar os testes manuais.
=> Garante que a lista de author_meta seja objetos AuthorMeta.

airflow/dags/operations/sync_kernel_to_website_operations.py, airflow/tests/test_sync_kernel_to_website.py
Esse PR é uma melhoria no algoritmo que garante que não seja adicionado campos vazios na entidade author_meta
Por commit. 
Sugiro que seja utilizado os teste automático para testar esse PR, segue: 
```
docker-compose -f docker-compose-dev.yml exec opac-airflow python -m unittest -v
````
N/A
N/A
Esse PR é um melheria da atividade #290  
N/A
=> Melhora o cadastro do authors_meta para garantir que não exista valores vazios.

airflow/dags/operations/sync_kernel_to_website_operations.py, airflow/tests/test_sync_kernel_to_website.py
Esse PR garante que o ``suffix`` esteja no nome do author.
Por commit.
Sugiro rodar os teste para assegurar que essa implementação está funcionando.
```
docker-compose -f docker-compose-dev.yml exec opac-airflow python -m unittest -v
```
Após atualizado o ambiente é necessário um reprocessamento dos artigos.
N/A
Tíquete referente a essa atividade: 
https://github.com/scieloorg/opac/issues/2017
N/A
=> Adiciona o ``suffix``  no nome do autor. 

airflow/dags/operations/sync_kernel_to_website_operations.py
Corrige o erro `Unexpected error 'unhashable type: 'BaseList'` que ocorre porque os valores do dicionário `scielo_pids` são do tipo `str` e `list`. No caso, só interessa os valores de `scielo_pids['other']`.
por commits
Veja em #295 a seção como reproduzir o erro 
n/a
n/a
#295 
n/a
=> Corrige o erro `Unexpected error 'unhashable type: 'BaseList'`

airflow/dags/sync_kernel_to_website.py
Adiciona o histórico do periódico e o próximo título caso exista.
Por commit 
Necessário ter um instância local e rodar a DAG: **sync_kernel_to_website**
Para ter efeito essa mudança é necessário que o kernel recebe uma alteração na lista de **/changes** para garantir que os periódicos sejam atualizados.
Imagem com o trecho da alteração na DAG: 
Esse ajuste faz parte da resolução dos tíquetes:  #1197 #1973 #1972 do OPAC.
N/A
=> Adiciona o histórico do periódico e o próximo título caso exista.

airflow/dags/sync_kernel_to_website.py
Adiciona o título anterior do periódico
Por commit. 
Necessário ter um instância local e rodar a DAG: **sync_kernel_to_website**
Para ter efeito essa mudança é necessário que o kernel recebe uma alteração na lista de /changes para garantir que os periódicos sejam atualizados.
N/A
N/A
Esse ajuste faz parte da resolução dos tíquetes: #1197 #1973 #1972 do OPAC.
=> Adiciona o título anterior do periódico

airflow/dags/sync_kernel_to_website.py
Adiciona um novo operador que irá enviar um e-mail após todos os passos do processamento excutado.
Avaliando o módulo: **airflow/dags/sync_kernel_to_website.py**
Subir uma instância do opac-airflow e executar a DAG de sync_kernel_to_website
**IMPORTANTE**: se existe um "skipped" em qualquer passo esse e-mail não será enviado o que é o comportamento esperado. A ausência dessa (e-mail) indica que o processamento não executou corretamente.
**IMPORTANTE**: Atualmente quando exite uma falha no processamento está sendo disparado um e-mail para **infra@scielo.org**, sugiro que seja adicionado os e-mail dos desenvolvedores.
Necessário uma nova variável com a lista de e-mails exemplo: Exemplo dessa variável: export
EMAIL_NOTIFICATION_RECIPIENTS=publicacao@scielo.org,gestao.editorial@scielo.org,prod …
=> Adiciona um novo operador que irá enviar um e-mail após todos os passos do processamento excutado.

airflow/dags/operations/sync_kernel_to_website_operations.py
Adiciona na (recurso) de descobertas dos artigos relacionados a capacidade de tratar mais um artigo com o mesmo **DOI**.
Adiciona melhorias nas mensagens.
Garante que seja pesquisado na base de dados apenas artigos públicos.
Pelo módulo airflow/dags/operations/sync_kernel_to_website_operations.py
Para testar manualmente é necessária uma errata ou retratação, ou adendo e garantir que esta relacionando um **DOI** duplicado na base de dados do site. 
Quando é encontrado mais de um é elegido para o relacionamento o primeiro encontrado, também esta sendo logado os demais encontrados.
Veja as massagens: 
N/A
N/A
=> Adiciona no recurso de descobertas dos artigos relacionados a capacidade de tratar mais um artigo com o mesmo DOI.

airflow/dags/operations/sync_kernel_to_website_operations.py
Corrige bug, inserido no tk309
```
[2021-11-29 18:18:37,140] {sync_kernel_to_website_operations.py:613} ERROR - Could not register document 'Y59FZXNc7JNKv3zNqmtwDht'. Unexpected error 'name 'new_doc' is not defined'.
[2021-11-29 18:18:37,169] {crypto.py:78} WARNING - cryptography not found - values will not be stored encrypted.
```
por commits
Executando `sync_kernel_to_website` para `Y59FZXNc7JNKv3zNqmtwDht` que é um documento que tem o mesmo doi de 
https://www.scielo.br/j/cadbto/a/vv7N59KhLSVGpyGRSvZybCJ/?lang=es
n/a
n/a
#309
n/a
=> obtém o `new_doc` usando o `document_id`

airflow/dags/operations/sync_kernel_to_website_operations.py
Corrige bug inserido por PR 311
```
[2021-11-29 19:15:18,764] {sync_kernel_to_website.py:198} INFO - Got bundle_id and order from Kernel: 2526-8910-2021-v29 {'id': 'Y59FZXNc7JNKv3zNqmtwDht', 'order': '00306'}
[2021-11-29 19:15:18,765] {sync_kernel_to_website_operations.py:698} INFO - Get doi from kernel
[2021-11-29 19:15:18,835] {sync_kernel_to_website_operations.py:613} ERROR - Could not register document 'Y59FZXNc7JNKv3zNqmtwDht'. Unexpected error ''QuerySet' object has no attribute 'title''.
[2021-11-29 19:15:18,875] {crypto.py:78} WARNING - cryptography not found - values will not be stored encrypted.
```
por commits
Ver #311
o revisor a fim de facilitar o entendimento da …
=> Corrige bug inserido por PR 311

airflow/dags/operations/sync_kernel_to_website_operations.py, airflow/dags/sync_kernel_to_website.py, requirements.txt
Adiciona a capacidade de armazenar o material suplementar. 
Sugiro que verifique principalmente pelo módulo: **airflow/dags/operations/sync_kernel_to_website_operations.py**
Para realizar um teste manual é possível adicionando o PID v3: **d6DyD7CHXbpTJbLq7NQQNdq** como **orphan** no opac-airflow e verificando que é encontrado material suplementar para o registro.
Veja: 
Essa atividade é essencial para resolver o legado do SciELO com artigos com material suplementar e os novos registros, bem como uma (URL) para resolução no site. 
Exemplo de um registro com material suplementar na base de dados: 
#315 
N/A
=> Adiciona a capacidade de armazenar o material suplementar.

airflow/dags/common/sps_package.py, airflow/dags/operations/sync_kernel_to_website_operations.py
Adiciona a capacidade de cadastrar os DOIs com idioma.
Por commit 
Subir uma instância local e colocar o PID V3: **mTSNspjDVVkVfz8k3RdPfmx** como orfão.
Realizado teste locais em fase de desenvolvimento.
#322 
N/A
=> Adiciona a capacidade de cadastrar os DOIs com idioma.

airflow/dags/operations/sync_kernel_to_website_operations.py
Adiciona um tratamento de erro no momento de cadastrar os suplementos do artigo.
Por commit.
Executando manualmente com o **id**: 6ddGXjtf5smsBPKXdgSK6Rk
Esse PR visa garantir que os artigos sejam inseridos mesmo que contenha erro no momento de cadastro dos suplementos, também foi adicionado uma impressão do Material Suplementar para efeito de verificação.
N/A
Essa é um ajuste do PR: https://github.com/scieloorg/opac-airflow/pull/321
N/A
=> Adiciona um tratamento de erro no momento de cadastrar os suplementos do artigo.

airflow/dags/common/hooks.py
Trata erro de conexão com o **minio.scielo.br** e resolução de nomes para:  **manager-postgresql.scielo.org**
Remove no momento de conexão com o **minio.scielo.br** a restrição de retentar somente em erros da ``requests``
Adiciona tentativas na função hooks:add_execution_in_database, pois estamos com problema de resolução de nome para o nome: manager-postgresql.scielo.org
Mensagem de erro ao tentar conectar com o manager-postgresql.scielo.org:
```
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "manager-postgresql.scielo.org" to address: Try again
```
Por commit
Para rodar manualmente é preciso executar o [pre_sync_documents_to_kernel](https://airflow.scielo.br/admin/airflow/tree?dag_id=pre_sync_documents_to_kernel) e depois o …
=> Trata erro de conexão e resolução de nomes.

airflow/dags/operations/sync_kernel_to_website_operations.py
Garante que em caso de o artigo não ter fascículo, não será considerado um documento repetido.
Por commit 
Executando a DAG sync_kernel_to_website.py
Esse ajuste tem como intenção evitar o erro: 
N/A
N/A
N/A
=> Garante que em caso de o artigo não ter fascículo, não será considerado um documento repetido.

README.md, airflow/dags/sync_documents_to_kernel.py, airflow/dags/sync_external_content_to_website.py, requirements.txt
Adiciona a execução automática da dag ``sync_kernel_to_website`` na dag ``sync_documents_to_kernel``.
Adiciona um agendamento para a dag ``external_content`` At 00:00 on Saturday
Atualiza o packtools para a versão 2.9.5.
Documenta a sequência de execução das DAGs
Por commit 
Executando a DAG sync_documents_to_kernel e verificando que a DAG sync_kernel_to_website é executada.
N/A
N/A
N/A
N/A
=> Auto run sync to site

airflow/dags/common/airflow_functions.py, airflow/dags/sync_documents_to_kernel.py
Adiciona uma condicional para iniciar a execução do **sync_kernel_to_website**. 
A condição deve ser a última DagRun.
Sugiro por commit.
Executando a dag **sync_documents_to_kernel** com o disparo de diversos DagRun.
A ideia dessa solução é avaliar se é a última DagRun caso seja dispara o próxima DAG. 
Testes realizados localmente: 
N/A
N/A
=> Adiciona uma condicional para iniciar a execução do sync_kernel_to_website. 

airflow/dags/sync_kernel_to_website.py
Ao registrar os dados de `issue` no site, deixar `issue.is_public = False` se não tiver documentos.
Esta funcionalidade é importante se os dados de entrada forem a partir da base de dados `issue` que contém dados de fascículos ainda em preparação. Com isso, é possível disparar a DAG `sync_isis_to_kernel` simultaneamente ao `GeraPadrao.bat` e, não posterior a ele, adiantando o processo de publicação. 
por commits
Deve-se executar o sync_isis_to_kernel usando uma base de dados issue com todos os fascículos, sendo que alguns deles não tenham os respectivos documentos prontos.
Não resolve 100% dos casos, pois não verificar se os documentos estão com valor `is_public == True` nem avalia a data de publicação `pub_date` para verificar se está em embargo.
n/a …
=> Estabelecer que `issue.is_public` é `False` se não contém documentos

airflow/dags/operations/sync_documents_to_kernel_operations.py, airflow/dags/sync_documents_to_kernel.py, airflow/tests/test_sync_documents_to_kernel.py, airflow/tests/test_sync_documents_to_kernel_operations.py
Usa o pacote não otimizado na ausência do pacote otimizado
por commits
não é conhecido a causa do erro de leitura do arquivo otimizado no momento de executar a tarefa `register...`. Aparentemente o pacote foi criado na tarefa anterior.
n/a
n/a
#343 
n/a
=> Usa o pacote não otimizado na ausência do pacote otimizado

airflow/dags/operations/sync_kernel_to_website_operations.py, airflow/dags/sync_kernel_to_website.py
Atualiza status do fascículo `is_public = True`
por commits
.
Aparentemente o problema acontece porque o `issue.is_public` tem valor igual a `false` e não é modificado após documentos serem ingressados nele.
.
.
.
=> Atualiza status do fascículo `is_public = True`

airflow/dags/operations/docs_utils.py
Remove o '.' (ponto) da extensão do arquivo para atribuir o mimetype
Por commit 
Executando localmente o airflow com o seguinte documento como orfão: ["vy7RnrNvd5B4rrCCX6vVx4d"]
N/A
N/A
https://github.com/scieloorg/opac/issues/2019
N/A
=> Remove o '.' (ponto) da extensão do arquivo para atribuir o mimetype

airflow/dags/operations/sync_kernel_to_website_operations.py
Garante que o campo de relacionamento com outro artigo esteja vazio.
Por commit 
Necessário subir uma instância local e realizar o processamento de sincronização com o site.
Foram realizados testes locais com um artigo com o campo related_articles e submetendo um novo registro com o mesmo **id** para sem o related_articles para seja garantido que seja removido! 
N/A
https://github.com/scieloorg/opac-airflow/issues/369
N/A
=> Garante que o campo de relacionamento com outro artigo esteja vazio.

airflow/dags/operations/sync_kernel_to_website_operations.py
Garante que seja obtido somente a traduções para seção e os idiomas quanto sub_article type=='translation'
Por commit 
Para testar manualmente é necessário executar o processamento do airflow para pelo menos um arquivo.
Essa atividade tentar resolver problemas com o Issue TOC reportados pela BAK(Bakhtiniana: Revista de Estudos do Discurso), link de exemplo: https://www.scielo.br/j/bak/aop
N/A
N/A
N/A
=> Garante que seja obtido somente a traduções para seção e os idiomas quanto sub_article type=='translation'
