.github/pull_request_template.md, airflow/Dockerfile, airflow/airflow.cfg, airflow/dags/read_documetstore_changes.py, docker-compose.yml
Adiciona a capacidade de obter a lista de mudanças realizadas no Kernel e cadastra as mudanças no site.
No módulo: airflow/dags/read_documetstore_changes.py:**register_journals**
**IMPORTANTE**: Configure as variáveis de ambiente: 
```
KERNEL_URL
OPAC_MONGODB_NAME 
OPAC_MONGODB_HOSTNAME 
OPAC_MONGODB_USERNAME 
OPAC_MONGODB_PASS 
```
Se o banco de dados não tiver autenticação!, deixar as variáveis OPAC_MONGODB_USERNAME e OPAC_MONGODB_PASS vazias.
docker-compose up -d
Para que tenha em mente o retorno de um item da API de mudança: 
`
{
id: "/journals/0000-0000-00-00-1",
timestamp: "2019-03-22T18:59:32.654875Z"
},
`
Este item é composto por duas chaves ``id`` e  ``timestamp``
Uma imagem da DAG: 
Uma imagem da API de mudança: 
Uma imagem do endpoint de journal: 
Uma imagem do registro …
=> Obtém a lista de mudanças dos periódico e cadastra no banco do Site

airflow/dags/kernel_changes.py
Obtém Fascículos e Artigos e registra no banco de dados do Site.
No módulo: **airflow/dags/kernel_changes.py:register_issues** 
**airflow/dags/kernel_changes.py:register_documents**
Veja: 
opac_conn: 
kernel_conn:
Adicionado no item anterior
Quando aplicável e se fizer possível adicione screenshots que remetem a situação gráfica do problema que …
=> Obtém Fascículos e Artigos e registra no banco de dados do Site.

airflow/dags/kernel_changes.py
Continua cadastrando os fascículos, porém agora com a referência para o Journal. Também foi melhorado a infra-estrutura de conexão com o banco de dados. 
Veja: 
opac_conn: 
kernel_conn:
Adicionado no item anterior
tk #6 
Não ha.
=> Realiza o cadastro dos fascículo com a referencia para o Journal

airflow/dags/kernel_changes.py
Continua cadastrando os artigos, porém agora com a referência para o Journal e Issue. Também foi reescrito a função transform_document para obter os dados do /front do Kernel.
**Importante:** A relação entre Journal -> Issue -> Article, devem existir!!!!!
Veja: 
opac_conn: 
kernel_conn:
Documentos cadastrados na Base de Dados do OPAC: 
tk #7 
Não ha.
=> Obter Documentos e registrar dados no banco do site

airflow/dags/kernel_changes.py
Marca os documentos como despublicados.
Veja: 
opac_conn: 
kernel_conn:
tk #8 
Não ha.
=> Marcar os documentos como despublicados

Makefile, airflow/Dockerfile-dev, docker-compose-dev.yml
Adiciona a infra estrutura de desenvolvimento
**IMPORTANTE:** Alterações na dags são refletidas diretamente no scheduler e no webserver.
Makefile
airflow/Dockerfile-dev
docker-compose-dev.yml
```python 
make help
make dev_compose_build
make dev_compose_initdb
make dev_compose_add_opac_conn
make dev_compose_add_kernel_conn
```
Esses comandos são para iniciar uma nova instância de opac-airflow
tk #5 
Não há
=> Adiciona a infra estrutura de desenvolvimento

airflow/dags/kernel_changes.py
Adiciona um EmbeddedDocument LastIssue na entidade Journal.
airflow/dags/kernel_changes.py:register_last_issues
```
airflow run kernel_changes register_last_issues 2019-04-18
```
Essa é uma necessidade imposta pelo modelo do OPAC e garante que os últimos fascículos estejam disponíveis na entidade Journal.
**IMPORTANTE**: Para o caso de não existir fascículo para o periódico, estou registrando no log.
tk #24
Não há.
=> Adicionar a entidade Last Issue.

airflow/dags/kernel_changes.py
Adiciona os campos: 
```
xml = StringField()
translated_titles = EmbeddedDocumentListField(TranslatedTitle)
sections = EmbeddedDocumentListField(TranslatedSection)
abstracts = EmbeddedDocumentListField(Abstract)
keywords = EmbeddedDocumentListField(ArticleKeyword)
```
Para a revisão desse PR é possível verificar as alterações no módulo: **airflow/dags/kernel_changes.py**
Executando o container de desenvolvimento através do commando: make dev_compose_up
Adicionado todo os campos possíveis. 
N/A
https://github.com/scieloorg/opac-airflow/issues/18
N/A
=> Adiciona mais campos para a endidade article

airflow/dags/kernel_changes.py
Re-fatora a transformação dos documentos, passa a utilizar uma função mais fluída com tratamento de KeyError e IndexError.
No módulo **kernel_changes.py:379**
Executando o processamento do airflow e/ou utilizando a função **kernel_changes.pytransform_document(data)**, onde o parâmetro data é objeto do tipo **json**
=> Re-fatora a transformação dos documentos

airflow/dags/kernel_changes.py
Adiciona a capacidade de cadastrar fascículos orfãos.
Creio que no seguinte módulo seja possível validar essa alteração: 
_airflow/dags/kernel_changes.py:register_issues_
Executando manualmente o opac-airflow. 
N/A
N/A
Ticket #36 
N/A
=> Adiciona a capacidade de cadastrar fascículos orfãos.

airflow/dags/kernel_changes.py
Este PR simplifica a interpretação da API de mudanças, remove a necessidade de comparação entre a última mudança e as mudanças retornadas pela API.
- `airflow/dags/kernel_changes.py` L: `143`
Para testar este PR deve-se:
- Preencha a API de mudanças com pelo menos 1000 mudanças (só pra conferir a paginação);
- Rode a TASK `http_kernel_check` e `read_changes_task`;
- Observe a variável `change_timestamp` na interface `admin` do airflow e verifique que o `timestamp` é o mesmo da última mudança.
- [`DEBUG`] Observe a quantidade de tasks geradas logo após a leitura da API;
N/A
N/A
closes #42 
Indique as referências utilizadas para a elaboração do pull request.
=> Altera semântica na busca por novas modificações

airflow/dags/kernel_changes.py
Substitui o PR https://github.com/scieloorg/opac-airflow/pull/63 e acrescenta outras correções que fazem com que as tasks executem até o fim para o processamento da coleção Saúde Pública.
As modificações foram concentrados em um único arquivo, mas em pontos bastante distintos. Sugiro visualizar cada commit individualmente.
Sugiro utilizar o `publishing-showcase`, com uma instância de Kernel e OPAC devidamente instaladas.
n/a
n/a
#60 
n/a
=> Corrige fascículos e documentos órfãos, e outras coisas mais

airflow/dags/kernel_documents.py, airflow/tests/test_kernel_documents.py
Melhorias na task de deleção de documentos do Kernel, que foram identificadas no início do desenvolvimento do registro e atualização de documentos, que não poderia utilizar do mecanismo de leitura dos documentos para deleção, tornando-se assim, irrelevante.
Em `airflow/dags/kernel_documents.py`
`docker-compose -f docker-compose-dev.yml exec opac-airflow python -m unittest discover -v`
OU
- Criando pacote SPS e scilista em diretórios locais e configurando as variáveis pela interface do airflow:
* `SCILISTA_FILE_PATH`: caminho do arquivo `scilista.lst`
* `XC_SPS_PACKAGES_DIR`: diretório com pacotes SPS (.zips)
* `PROC_SPS_PACKAGES_DIR `: diretório de processamento
- Executar as tasks na sequencia:
* `docker-compose -f docker-compose-dev.yml exec opac-airflow …
=> Melhorias na task de deleção de documentos do Kernel

airflow/dags/common/sps_package.py, airflow/dags/operations/docs_utils.py, airflow/dags/operations/exceptions.py, airflow/dags/operations/sync_documents_to_kernel_operations.py, airflow/tests/test_docs_utils.py, airflow/tests/test_sync_documents_to_kernel_operations.py
Trata exceções durante a sincronização de documentos com o Kernel:
* Exceções durante a leitura e sincronização dos XMLs, passa para a leitura do próximo documento, sem parar o processo
* Exceções durante a leitura e sincronização de ativo digital ou manifestação, continua o processo de sincronização do documento, mesmo parcial
As únicas exceções que não são tratadas e que param o processo de sincronização são as relacionadas às conexões com o Object Store (Minio) e o Kernel
É recomendado que a revisão seja feita pelos commits.
`docker-compose -f docker-compose-dev.yml exec opac-airflow python -m unittest -v`
OU
- Criando pacote SPS e scilista em diretórios locais e configurando as variáveis pela interface do airflow:
* `SCILISTA_FILE_PATH`: caminho do …
=> Trata exceções durante a sincronização de documentos com o Kernel

airflow/airflow.cfg
Esse PR visa alterar o arquivo de configuração (`airflow.cfg`), para atender as modificações da versão 1.10.4 do apache-airflow que foi atualizada no projeto
Mais detalhes esta no TK #84 
Pelo arquivo
* `airflow/airflow.cfg`
* Pelos testes unitarios
```
docker-compose -f docker-compose-dev.yml exec opac-airflow python -m unittest -v
```
OU
* Apos atualizar o código, recompilar a docker e verificar que o comportamento do Airflow, permanesse inalterado
Essa se alteração se da devido a alteração de versão do `apache-airflow`
N/A
#83 
Propria saída de log
=> Ajustes no arquivo de configuração do airflow

airflow/dags/kernel_changes.py
Adiciona os tipos de issue ao kernel changes.
- `airflow/dags/kernel_changes.py` L `379`
- Execute o `kernel_changes` com uma base vazia do OPAC
N/A
N/A
fix #93
N/A
=> Adiciona os tipos de issue ao kernel changes

airflow/dags/operations/sync_documents_to_kernel_operations.py, airflow/tests/test_sync_documents_to_kernel_operations.py
Este pull request corrige o erro apresentado pela issue #99. Também restringe a atualização da lista de `items` dos `DocumentsBundles` a diferenças entre a `nova lista` e a lista `atual` de `items`.
- `airflow/dags/operations/sync_documents_to_kernel_operations.py` L: `231`
Para testar este pull request deve-se:
- Espelhar a base de dados do scielo br ou sp [1];
- Sincronizar um primeiro pacote SPS referido a um bundle em específico [2];
- Sincronizar um novo pacote SPS referido ao mesmo bundle anterior MAS com documentos diferentes[3];
- Verificar que a lista foi atualizada e os documentos primeiros foram mantidos.
N/A
N/A
closes #99
N/A
[1] - CURL para criar uma issue de MOCK (remove a necessidade de espelhamento da base)
```shell
curl -X PUT -H 'Accept: application/json' \
-H …
```
=> Corrige link entre documents e documentsbundles

airflow/dags/sync_isis_to_kernel.py, airflow/tests/test_sync_isis_to_kernel.py, airflow/tests/test_sync_kernel_to_website.py, requirements.txt
Troca publication_season por publication_months 
- airflow/dags/sync_isis_to_kernel.py
não consegui rodar os testes automatizados
n/a
n/a
#109
n/a
=> Troca de publication_season para publication_months

airflow/dags/sync_documents_to_kernel.py
Como todos os operadores das tarefas da DAG `sync_documents_to_kernel` foram alteradas para `ShortCircuitOperator`, é necessário que, em caso de continuidade do fluxo, o retorno dos *callables* deve ser `True`.
Em `airflow/dags/sync_documents_to_kernel.py`
- Execute a DAG `sync_documents_to_kernel` para importar um pacote SPS com documentos para registro/atualização
- Todas as tarefas da DAG devem ser executadas
N/A
N/A
N/A
http://airflow.apache.org/docs/1.10.4/_api/airflow/operators/python_operator/#airflow.operators.python_operator.ShortCircuitOperator
=> Corrige DAG de sync de documentos p/ kernel

airflow/dags/sync_isis_to_kernel.py, airflow/dags/sync_kernel_to_website.py, airflow/tests/test_sync_isis_to_kernel.py
Executa sincronizacao de dados do campo publisher da base isis para o kernel
Executa a sincronizacao dos dados do campo "institution_responsible_for" (kernel) para o campo "publisher" do site
airflow/dags/sync_isis_to_kernel.py
airflow/dags/sync_kernel_to_website.py
n/a
n/a
n/a
https://github.com/scieloorg/opac/issues/1453
n/a
=> Executa sincronização de dados do campo publisher da base isis para o kernel e do kernel para o site

airflow/dags/sync_kernel_to_website.py, airflow/tests/fixtures/kernel-journals-1678-4464.json
Este pull request trás modificações já aplicadas ao ambiente `dsteste` deste **Janeiro** mas que por algum motivo desconhecido não estavam no repositório de código.
N/A
Elas já foram testadas pelos últimos 4 processamentos completos.
N/A
N/A
N/A
N/A
=> Corrige o registro de periódicos e artigos no Website

airflow/dags/common/hooks.py
Altera as configurações de retentativas das conexões HTTP para obter variável configurável. Caso não seja informada, uma tentativa a mais do que estava anteriormente é passada como padrão. Para dar mais flexibilidade, ao invés de colocar uma tentativa a mais, colocou-se um valor padrão e a possibilidade de configurar de acordo com a necessidade do ambiente.
Em `airflow/dags/common/hooks.py`
1. Execute qualquer DAG que faça conexão com HTTP com algum servidor que não responda;
2. Verifique o número de retentativas. Deve ser 5;
3. Adicione variável de ambiente `HTTP_HOOK_RUN_RETRIES` no Airflow acessando *Admin > Variables*;
4. Execute o passo 1 novamente;
5. Verifique o número de retentativas. Deve ser o valor configurado na variável.
Tivemos alguns problemas de timeout em algumas …
=> Altera número de tentativas da conexão HTTP para ser configurável

proc/GeraPadrao.bat, proc/PrepSyncToKernel.bat, proc/PrepSyncToKernel.ini.template
Melhora o procedimento de ingresso no Airflow  de pacotes provenientes do XC, considerando:
- mover os pacotes ao invés de copiar
- não tentar mover pacotes inexistentes
- informar se o pacote inexistente é ou não ahead, pois se é ahead é talvez ok, senão é erro
- remover repetição na scilista
- melhora a interação com o usuário, gerando arquivo de log e resumo do resultado
- o arquivo de log ficará disponível para o Airflow juntamente com os pacotes + scilista. Ex.: 
[PrepSyncToKernel.log](https://github.com/scieloorg/opac-airflow/files/4921181/PrepSyncToKernel.log)
por commits, a partir de [aa85bae](https://github.com/scieloorg/opac-airflow/commit/aa85bae86fe4116e6691e6230ea93538eba29f32)
1. Crie um arquivo chamado SCILISTA.lst com o seguinte conteúdo:
```
abc v1n1
xyz v2n2 del
csp …
```
=> Faz melhorias no script PrepSyncToKernel.bat que fornece pacotes para o SPF via GeraPadrao

airflow/dags/operations/pre_sync_documents_to_kernel_operations.py, airflow/tests/test_pre_sync_documents_to_kernel_operations.py
Faz com que a "Pré-sincronização dos documentos para o Kernel" possa ser reexecutada n vezes e ainda assim o retorno da função seja o mesmo, ou seja, uma lista com os nomes dos arquivos que devem estar na pasta `destino` na ordem da scilista e ordem de nome de arquivo.
por commits, https://github.com/scieloorg/opac-airflow/pull/183/commits/579bd98c8fdaa35060d81c9c666ea3577b5d32d3
Com diretório origem contendo pacotes SPS gerados pelo XC e scilista com pacotes relacionados:
Caminho feliz
1. Configure o airflow, apontando para o diretório origem, um diretório destino de trabalho e o caminho da scilista
2. Execute a DAG `pre_sync_documents_to_kernel`
3. Verifique se os pacotes de todos os fascículos relacionados na scilista existentes no diretório origem foram copiados
4. Verifique se a …
=> Faz com que a "Pré-sincronização dos documentos para o Kernel" possa ser reexecutada n vezes e ainda assim o retorno da função seja o mesmo

proc/PrepSyncToKernel.bat
Corrige a condição de existência de arquivos de determinado padrão de nomes
por commits
Veja a mesma seção em #181
n/a
No homolog-metodologia
```shell script
[roberta.takenaka@homolog-metodologia proc]$ ls -ltr DESTINO/
total 0
[roberta.takenaka@homolog-metodologia proc]$ ls -ltr ORIGEM
total 8
-rw-r--r--. 1 roberta.takenaka scielo.desenv    0 Jul 20 16:26 x_abc_2020nahead.zip
-rw-r--r--. 1 roberta.takenaka scielo.desenv    0 Jul 20 16:26 zzz_v8.zip
-rw-r--r--. 1 roberta.takenaka scielo.desenv    0 Jul 20 16:26 0_abc_v1n1.zip
-rw-r--r--. 1 roberta.takenaka scielo.desenv    0 Jul 20 16:26 axy_2020nahead.zip
-rw-r--r--. 1 roberta.takenaka scielo.desenv    0 Jul 20 16:26 x _abc_v1n1.zip
-rw-r--r--. 1 roberta.takenaka scielo.desenv   71 Jul 20 16:28 xlista
-rw-r--r--. 1 roberta.takenaka …
```
=> [PrepSyncToKernel.bat] Corrige a condição de existência de arquivos de determinado padrão de nomes

Dockerfile
Este pull request adiciona a capacidade manipulação de imagens do tipo `tiff`, tal característica é necessária durante a task de otimização de imagens da DAG `sync_documents_to_kernel`;
- Em b2ab507
- Baixar o pacote [1];
- Entre no container do airflow por meio do `docker exec ... bash`;
- Adicione o pacote [1] ao diretório `/usr/local/airflow/proc/`;
- Abra um IDLE python;
- Execute o trecho de código:
```python
import airflow
from dags.operations.sync_documents_to_kernel_operations import optimize_sps_pkg_zip_file
pacote = "/usr/local/airflow/proc/2020-07-28-17-50-33-988846_mioc_v115.zip"
optimize_sps_pkg_zip_file(pacote, "/tmp")
```
- Verifique que não houve erro ao otimizar as imagens;
- Copie a o resultado de saída do comando de …
=> Adiciona biblioteca tiff-dev para que o Pillow dê suporte a este tipo de imagem

README.md, airflow/dags/check_website.py, airflow/dags/operations/check_website_operations.py, airflow/dags/sync_kernel_to_website.py, airflow/tests/test_check_website.py, airflow/tests/test_check_website_operations.py, proc/CallGeraUriList.bat, proc/GeraPadrao.bat, proc/GeraUriList.bat, proc/pft/gera_uri_list.pft
Dada uma scilista, gera a lista de URI e verifica se estão disponíveis.
por commits
**Teste da Execução do GeraPadrao**
0. Execute `export CISIS_DIR=cisis` para indicar o caminho do mx
1. Configure o arquivo `proc/SyncToKernel.ini`
2. Execute o `GeraPadrao.bat` em um local onde tenha acesso às bases de dados de `bases-work`, pois é a partir da scilista e destas bases que o arquivo `uri_list_<data>.lst` será gerado.
**Teste da DAG**
0. No docker-compose-dev.yml, garanta que tenhas os volumes (exemplo):
```
- ./test_source:/usr/local/xc_packages
- ./test_dest:/usr/local/proc_airflow
```
Sendo que `./test_source` é onde estaria o `uri_list_<data>.lst`
Sendo que `./test_dest` é para onde o airflow copiará `uri_list_<data>.lst` de `./test_source`.
1. Execute o comando
```
docker-compose -f …
```
=> [FASE 3] Automatiza a verificação das URI do site a partir da scilista 

README.md, airflow/dags/check_website.py, airflow/dags/common/async_requests.py, airflow/dags/operations/check_website_operations.py, airflow/tests/test_check_website.py, airflow/tests/test_check_website_operations.py
Permite a configuração dos valores de timeout para as requisições sequenciais e para as requisições simultâneas para a DAG check_website
por commits
Preencha as variáveis relacionadas com o timeout (veja README.md, em um dos commits)
Ver seção "Como este poderia ser testado manualmente", do #216
n/a
n/a
#221 , #211
n/a
=> Permite a configuração dos valores de timeout para as requisições sequenciais e para as requisições simultâneas para a DAG check_website

airflow/dags/operations/sync_kernel_to_website_operations.py, airflow/tests/test_sync_kernel_to_website.py
Este PR corrige o problema de resumos sendo colocados na base do site com texto vazio.
Commit 1706d72.
- Uma instância de Kernel e o banco de dados MongoDB com a base de dados do OPAC são necessárias
- Insira um documento no Kernel, seja por ingestão direta ou migração, sem resumo
- Execute a DAG `sync_kernel_to_website`
- Verifique no OPAC que o documento não possui resumo (na base de dados ou via interface Web, no Issue TOC)
- Repita o segundo e terceiro passo com um documento com `trans-abstract` e `sub-article`
- Verifique no OPAC que o documento possui resumo (na base de dados ou via interface Web, no Issue TOC)
Este problema foi identificado na navegação do site, que está apresentando a presença de resumos mas sem o texto.
.
Fix https://github.com/scieloorg/opac/issues/1730
.
=> Corrige problema de resumos sem texto

airflow/dags/sync_kernel_to_website.py, airflow/tests/test_sync_kernel_to_website.py
=> Ajustes no caso de ahead (complementa PR #280)

airflow/dags/operations/sync_kernel_to_website_operations.py, airflow/tests/fixtures/kernel-document-front-s1518-8787.2019053000621.display_fmt.json, airflow/tests/test_sync_kernel_to_website.py
Se no front houver `display-format`, dar preferência para usar isso para preencher `title` e `translated_titles`
por commits
executando a entrada/atualização de um documento
n/a
n/a
https://github.com/scieloorg/opac/issues/1484
n/a
=> Se no front houver `display-format`, dar preferência para usar isso para preencher `title` e `translated_titles`

airflow/dags/operations/sync_kernel_to_website_operations.py, airflow/tests/test_sync_kernel_to_website.py
Resolve problemas de inconsistências: documentos "delete" no kernel mas publicados no site e documentos publicados em repetição.
Por commits
Identificar um documento com status "delete" no kernel e que está publicado no site.
Inserir o pid v3 na variável `orphan_documents`.
Executar o `sync_kernel_to_website`.
Verificar que o documento ficou como despublicado.
Identificar documento que esteja duplicado no website.
Inserir o pid v3 na variável `orphan_documents`.
Executar o `sync_kernel_to_website`.
Verificar que as repetições ficaram como despublicado e o documento "vigente" fica como publicado e em `scielo_pids` conterá 
```json
{"other": ["pid 1 dos repetidos", "pid 2 dos repetidos"]}
```
A duplicidadade ocorreu ao migrar aop para regular.
A duplicidadade ocorreu quando mudado o PID. …
=> Despublica documentos do site, se ausentes no kernel ou "duplicados" no site

airflow/dags/operations/sync_kernel_to_website_operations.py, airflow/tests/test_sync_kernel_to_website.py, requirements.txt
Popula a entidade AuthorMeta.
Sugiro que seja avaliado por commit.
É importante rodar os testes unitários, é possível utilizando o comando: 
```
docker-compose -f docker-compose-dev.yml exec opac-airflow python -m unittest -v
```
Não realizei teste manuais! 
@robertatakenaka gostaria de verificar contigo uma forma fácil de realizar testes manuais no opac-airflow.
**IMPORTANTE**: Sugiro que realizar um testes manuais em ambiente de homologação.
Essa atividade foi motivada pela seguinte necessidade no OPAC: https://github.com/scieloorg/opac/issues/1952 
https://github.com/scieloorg/opac/issues/1952
=> Popula a entidade AuthorMeta no momento de cadastro dos artigos.

airflow/dags/operations/sync_kernel_to_website_operations.py
Fale sobre o propósito do pull request como por exemplo: quais problemas ele soluciona ou quais features ele adiciona.
Indique o caminho do arquivo e o arquivo onde o revisor deve iniciar a leitura do código.
Estabeleça os passos necessários para que a funcionalidade seja testada manualmente pelo revisor.
Indique uma issue ao qual o pull request faz relacionamento.
Indique as referências utilizadas para a elaboração do pull request.
=> Corrige bug inserido por PR 312

airflow/dags/sync_isis_to_kernel.py
Fale sobre o propósito do pull request como por exemplo: quais problemas ele soluciona ou quais features ele adiciona.
Indique o caminho do arquivo e o arquivo onde o revisor deve iniciar a leitura do código.
Estabeleça os passos necessários para que a funcionalidade seja testada manualmente pelo revisor.
Indique uma issue ao qual o pull request faz relacionamento.
Indique as referências utilizadas para a elaboração do pull request.](https://github.com/robertatakenaka/opac-airflow/pull/new/patch_journ …
=> Patch journal fix 2

airflow/dags/operations/sync_kernel_to_website_operations.py
Adiciona o tipo **"comentário de artigo"** na entidade de artigos relacionados. 
Por commit, considere somente as alterações realizadas na linha **567**
Iniciando o opac-airflow e processando um artigo que seja artigo de comentário, segue uma lista dessas (categorias) de artigo: https://docs.google.com/spreadsheets/d/1Ss5IXfgSFC_zm5U2zlhk4B8htSE2Sfc3Z7H1MKlEY5g/edit#gid=234712383
N/A
N/A
N/A
N/A
=> Adiciona mais um tipo como um artigo relacionado ``article-commentary``

airflow/dags/operations/sync_kernel_to_website_operations.py, airflow/dags/sync_kernel_to_website.py
Adiciona uma lista de falha para que possa ser avaliado e resubmetido.
Por commit. 
Para testar sugiro adicionar um artigo que gere um erro.
Essa atividade visa nos capacitar em saber quais os PID. que não foram cadastrados no site.
N/A
N/A
=> Adiciona uma lista de falha para que possa ser avaliado e resubmetido.

airflow/dags/common/mime.py, airflow/dags/operations/docs_utils.py
Adiciona um módulo com **mimetypes** e no momento de cadastra os assets no minio que verificado o **mimetype**.
Por commit 
Rodando o sync_documents_to_kernel.
N/A
N/A
Esse PR resolve o tíquete: https://github.com/scieloorg/opac-airflow/issues/303
N/A
=> Adiciona um módulo com mimetypes e no momento de cadastra os assets no minio que verificado o mimetype.

airflow/dags/operations/sync_kernel_to_website_operations.py
Garante que seja pego sempre o último item da lista de asset do kernel para avaliarmos se contém ou não supplemento.
Por commit. 
Processamento um artigo que contenha suplemento e mais de uma versão de asset. 
N/A
N/A
Esse resolve problemas descritos no documento: https://docs.google.com/document/d/1gB9EffmV2MhSRU1ZKzm8RemM5_gdGmXktTNBk_memrA/edit#
N/A
=> Garante que seja pego sempre o último item da lista de asset do kernel para avaliarmos se contém ou não supplemento.

airflow/dags/operations/sync_kernel_to_website_operations.py
Registrar como author somente `contrib[@contrib-type='author']`
por commits
Ver #334
n/a
n/a
#334 
n/a
=> Considerar como autor somente `contrib[@contrib-type='author']`

airflow/dags/operations/sync_kernel_to_website_operations.py, airflow/tests/fixtures/kernel_manifest.json, airflow/tests/test_sync_kernel_to_website.py
Corrige a obtenção / armazenamento dos materiais suplementares
por commits
Executar a DAG sync_kernel_to_website de um documento que tenha material suplementar.
n/a
n/a
#339
n/a
=> Corrige a obtenção / armazenamento dos materiais suplementares

airflow/dags/sync_isis_to_kernel.py
Insere tratamento de exceção em caso de `issue_as_kernel` falhar
Por commits
n/a
n/a
n/a
#387 
n/a
=> Insere tratamento de exceção em caso de `issue_as_kernel` falhar

airflow/dags/sync_isis_to_kernel.py
=> Resolve interrupção no processamento 10/05

Dockerfile
Fale sobre o propósito do pull request como por exemplo: quais problemas ele soluciona ou quais features ele adiciona.
Indique o caminho do arquivo e o arquivo onde o revisor deve iniciar a leitura do código.
Estabeleça os passos necessários para que a funcionalidade seja testada manualmente pelo revisor.
Indique uma issue ao qual o pull request faz relacionamento.
Indique as referências utilizadas para a elaboração do pull request.
=> Fix Dockerfile para instalar  dependências de pillow

airflow/dags/sync_kernel_to_website.py
Corrige #479 pois a solução foi incompleta por não resolver o retorno de `get_issue_order`.
Indique o caminho do arquivo e o arquivo onde o revisor deve iniciar a leitura do código.
Estabeleça os passos necessários para que a funcionalidade seja testada manualmente pelo revisor.
Indique uma issue ao qual o pull request faz relacionamento.
Indique as referências utilizadas para a elaboração do pull request.
=> Corrige try_register_issues para identificar corretamente o issue_order
